# Python Pandas Data Cleaning

In [1679]:
import pandas as pd
import numpy as np
df = pd.read_excel(r"D:\Private\555 sha\P\pandas-data-cleaning-project\data\raw_data.xlsx",keep_default_na=False, dtype="str")

# 🟢 LEVEL 1 — Basic Structural Cleaning

## Task 1 — Inspect the Dataset

**Find:**
- **Number of rows**
- **Number of columns**
- **Column names**
- **Data types**
- **Memory usage**
- **First 5 rows**
- **Last 5 rows**

In [1680]:
df.shape

(500, 11)

In [1681]:
df.columns

Index([' Employee ID ', 'NAME', 'Department', 'Age', 'Salary', 'Bonus',
       'Join Date', 'Email', 'Phone', 'Gender', 'Status'],
      dtype='str')

In [1682]:
df.dtypes

 Employee ID     str
NAME             str
Department       str
Age              str
Salary           str
Bonus            str
Join Date        str
Email            str
Phone            str
Gender           str
Status           str
dtype: object

In [1683]:
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0    Employee ID   500 non-null    str
 1   NAME           500 non-null    str
 2   Department     500 non-null    str
 3   Age            500 non-null    str
 4   Salary         500 non-null    str
 5   Bonus          500 non-null    str
 6   Join Date      500 non-null    str
 7   Email          500 non-null    str
 8   Phone          500 non-null    str
 9   Gender         500 non-null    str
 10  Status         500 non-null    str
dtypes: str(11)
memory usage: 307.0 KB

In [1684]:
df.head(5)

,Employee ID,NAME,Department,Age,Salary,Bonus,Join Date,Email,Phone,Gender,Status
0,E001,John Smith,IT,25,5000,500,unknown,noor.martin@hotmail.com,97474793157,M,N/A
1,E002,MARY JOHNSON,it,30,6000,null,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active
2,E003,,IT Department,35,7500.5,?,2020-03-19 00:00:00,mary.brown@yahoo,37773911,Female,A
3,E004,Sara Khan,HR,N/A,N/A,500,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive
4,E005,Robert Brown,Human Resources,42,8000,Unknown,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active

In [1685]:
df.tail(5)

,Employee ID,NAME,Department,Age,Salary,Bonus,Join Date,Email,Phone,Gender,Status
495,E496,Daniel Smith,Sales,45,unknown,-50,2019-02-09 00:00:00,emma.taylor@company.com,31753140,Female,ACTIVE
496,E497,Maya Ali,IT Department,32,4800,1000,2020-02-18,ryan.taylor@hotmail.com,974-5587-2645,m,ACTIVE
497,E498,Unknown,Marketing,27,N/A,300,2020-12-15 00:00:00,amira.moore@gmail.com,974-6740-1535,female,Inactive
498,E500,Hana Davis,Operations,38,6200,,16-10-2023,john..smith@gmail.com,974-7468-5012,male,INACTIVE
499,E500,Hana Davis,Operations,38,6200,,16-10-2023,john..smith@gmail.com,974-7468-5012,male,INACTIVE

# 🟢 LEVEL 1 — Basic Structural Cleaning

## Task 2 — Clean Column Names

**Convert column names into lowercase, remove extra spaces, and replace spaces between words with underscores.**

**Example:**
- `" Employee ID "` → `employee_id`
- `"NAME"` → `name`
- `"Department"` → `department`
- `"Join Date"` → `join_date`

In [1686]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(r"\s+","_", regex=True)
df.columns

Index(['employee_id', 'name', 'department', 'age', 'salary', 'bonus',
       'join_date', 'email', 'phone', 'gender', 'status'],
      dtype='str')

# 🟢 LEVEL 1 — Basic Structural Cleaning

## Task 3 — Remove Leading and Trailing Whitespace

**Clean leading and trailing whitespace from all string columns.**

**Examples:**
- `"     John Smith     "` → `"John Smith"`
- `"it          "` → `"it"`
- `"    2022-05-20     "` → `"2022-05-20"`

In [1687]:
for cl in df.select_dtypes(include="str").columns :
    df[cl] = df[cl].str.strip()
    df[cl] = df[cl].str.replace(r"\s+", " ", regex = True)    
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status
0,E001,John Smith,IT,25,5000,500,unknown,noor.martin@hotmail.com,97474793157,M,N/A
1,E002,MARY JOHNSON,it,30,6000,null,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active
2,E003,,IT Department,35,7500.5,?,2020-03-19 00:00:00,mary.brown@yahoo,37773911,Female,A
3,E004,Sara Khan,HR,N/A,N/A,500,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive
4,E005,Robert Brown,Human Resources,42,8000,Unknown,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active
5,E006,mohammed hassan,sales,twenty-eight,6500,-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive
6,E007,David Wilson,Sales,29,7200,500,2019-07-03,john.davishotmail.com,not available,f,active
7,E008,Lisa Thomas,SALES,,,null,2024-09-26 00:00:00,peter.wilson@company.com,55859430,unknown,active
8,E009,james miller,,150,9000,,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,,
9,E010,Emma Davis,Finance,-5,-5000,500,2020-05-19,adam.anderson@yahoo.com,6028 1693,FEMALE,active

# 🟢 LEVEL 1 — Basic Structural Cleaning

## Task 4 — Find Completely Empty Strings

- **Find cells containing empty strings (`""`) or strings with only whitespace (`"   "`).**
- **Replace them with `NaN`.**

In [1688]:
for cl in df.columns:
    df[cl] = df[cl].replace(r"^\s*$", np.nan, regex=True)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status
0,E001,John Smith,IT,25,5000,500,unknown,noor.martin@hotmail.com,97474793157,M,N/A
1,E002,MARY JOHNSON,it,30,6000,null,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active
2,E003,NaN,IT Department,35,7500.5,?,2020-03-19 00:00:00,mary.brown@yahoo,37773911,Female,A
3,E004,Sara Khan,HR,N/A,N/A,500,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive
4,E005,Robert Brown,Human Resources,42,8000,Unknown,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active
5,E006,mohammed hassan,sales,twenty-eight,6500,-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive
6,E007,David Wilson,Sales,29,7200,500,2019-07-03,john.davishotmail.com,not available,f,active
7,E008,Lisa Thomas,SALES,NaN,NaN,null,2024-09-26 00:00:00,peter.wilson@company.com,55859430,unknown,active
8,E009,james miller,NaN,150,9000,NaN,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN
9,E010,Emma Davis,Finance,-5,-5000,500,2020-05-19,adam.anderson@yahoo.com,6028 1693,FEMALE,active

# 🟢 LEVEL 2 — Missing Values

## Task 5 — Identify Missing Values

- **Identify missing values using `df.isna()`.**
- **Calculate the missing value count for every column.**

In [1689]:
missing_values = df.isna().sum()
missing_values

employee_id     0
name            1
department      1
age             1
salary          1
bonus          38
join_date       7
email           8
phone           4
gender         27
status         26
dtype: int64

# 🟢 LEVEL 2 — Missing Values

## Task 6 — Calculate Missing Percentage

- **Calculate the missing value count for every column.**
- **Calculate the missing percentage for every column.**

In [1690]:
missing_percentage = df.isna().mean() * 100.0
result = pd.DataFrame({
    "missing_count" : missing_values,
    "missing_percentage" : missing_percentage
})
result = result.reset_index(names="Column")
result

         Column  missing_count  missing_percentage
0   employee_id              0                 0.0
1          name              1                 0.2
2    department              1                 0.2
3           age              1                 0.2
4        salary              1                 0.2
5         bonus             38                 7.6
6     join_date              7                 1.4
7         email              8                 1.6
8         phone              4                 0.8
9        gender             27                 5.4
10       status             26                 5.2

# 🟢 LEVEL 2 — Missing Values

## Task 7 — Replace Fake Missing Values

**Convert the following fake missing values into actual `NaN`:**

- **`"N/A"`**
- **`"NULL"`**
- **`"unknown"`**
- **`"Unknown"`**
- **`""`** (empty string)

In [1691]:
fake_missing = ["N/A","NULL","unknown","Unknown","", "null"]
for cl in df.columns:
    df[cl] = df[cl].replace(fake_missing,np.nan)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status
0,E001,John Smith,IT,25,5000,500,NaN,noor.martin@hotmail.com,97474793157,M,NaN
1,E002,MARY JOHNSON,it,30,6000,NaN,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active
2,E003,NaN,IT Department,35,7500.5,?,2020-03-19 00:00:00,mary.brown@yahoo,37773911,Female,A
3,E004,Sara Khan,HR,NaN,NaN,500,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive
4,E005,Robert Brown,Human Resources,42,8000,NaN,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active
5,E006,mohammed hassan,sales,twenty-eight,6500,-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive
6,E007,David Wilson,Sales,29,7200,500,2019-07-03,john.davishotmail.com,not available,f,active
7,E008,Lisa Thomas,SALES,NaN,NaN,NaN,2024-09-26 00:00:00,peter.wilson@company.com,55859430,NaN,active
8,E009,james miller,NaN,150,9000,NaN,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN
9,E010,Emma Davis,Finance,-5,-5000,500,2020-05-19,adam.anderson@yahoo.com,6028 1693,FEMALE,active

## 🟢 LEVEL 2 — Missing Values

# Task 8 — Decide How to Handle Missing Values

**Missing-value treatment will be performed after completing the data-cleaning and data-type conversion tasks to avoid affecting subsequent analysis.**

**The appropriate strategy will be selected based on each column's meaning and the amount of missing data.**

# 🟢 LEVEL 2 — Missing Values

## Task 9 — Create Missing Indicators

**Create the following columns:**
- **`age_missing`**
- **`salary_missing`**
- **`email_missing`**
- **`phone_missing`**

**Example:**
- **`age = NaN` → `age_missing = 1`**
- **`age = 25` → `age_missing = 0`**

In [1692]:
missing_columns = ['age','salary','email','phone']
for cl in missing_columns:
    df[cl+"_missing"] = df[cl].isna().astype("int")
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25,5000,500,NaN,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,MARY JOHNSON,it,30,6000,NaN,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT Department,35,7500.5,?,2020-03-19 00:00:00,mary.brown@yahoo,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,Human Resources,42,8000,NaN,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,mohammed hassan,sales,twenty-eight,6500,-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29,7200,500,2019-07-03,john.davishotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,SALES,NaN,NaN,NaN,2024-09-26 00:00:00,peter.wilson@company.com,55859430,NaN,active,1,1,0,0
8,E009,james miller,NaN,150,9000,NaN,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5,-5000,500,2020-05-19,adam.anderson@yahoo.com,6028 1693,FEMALE,active,0,0,0,0

# 🟡 LEVEL 3 — Data Types

## Task 10 — Convert Age
**Currently:**
- **`"25"`**
- **`" 30 "`**
- **`"35"`**
- **`"twenty-eight"`**
- **`"N/A"`**
**Objective: Convert `age` into numeric values.**
**Expected result: Invalid values should become `NaN`**

In [1693]:
df["age"] = pd.to_numeric(df["age"], errors="coerce")
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000,500,NaN,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,MARY JOHNSON,it,30.0,6000,NaN,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT Department,35.0,7500.5,?,2020-03-19 00:00:00,mary.brown@yahoo,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,Human Resources,42.0,8000,NaN,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,mohammed hassan,sales,NaN,6500,-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200,500,2019-07-03,john.davishotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,SALES,NaN,NaN,NaN,2024-09-26 00:00:00,peter.wilson@company.com,55859430,NaN,active,1,1,0,0
8,E009,james miller,NaN,150.0,9000,NaN,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000,500,2020-05-19,adam.anderson@yahoo.com,6028 1693,FEMALE,active,0,0,0,0

# 🟡 LEVEL 3 — Data Types

## Task 11 — Convert Salary

**Currently:**
- **`"$5,000"`**
- **`"6000"`**
- **`"7,500.50"`**
- **`"8,000"`**

**Objective: Remove currency symbols and commas, then convert `salary` into numeric values.**

**Expected result:**
- **`5000`**
- **`6000`**
- **`7500.50`**
- **`8000`**

In [1694]:
df["salary"] = df["salary"].str.replace('$',"", regex=False)
df["salary"] = df["salary"].str.replace(',',"", regex=False)
df["salary"] = pd.to_numeric(df["salary"], errors="coerce")
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,500,NaN,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,MARY JOHNSON,it,30.0,6000.0,NaN,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT Department,35.0,7500.5,?,2020-03-19 00:00:00,mary.brown@yahoo,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,Human Resources,42.0,8000.0,NaN,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,mohammed hassan,sales,NaN,6500.0,-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,500,2019-07-03,john.davishotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,SALES,NaN,NaN,NaN,2024-09-26 00:00:00,peter.wilson@company.com,55859430,NaN,active,1,1,0,0
8,E009,james miller,NaN,150.0,9000.0,NaN,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500,2020-05-19,adam.anderson@yahoo.com,6028 1693,FEMALE,active,0,0,0,0

# 🟡 LEVEL 3 — Data Types

## Task 12 — Convert Bonus to Numeric

**Clean the `bonus` column and convert it to a numeric data type.**

**Example values:**
- **`"$750"`**
- **`"1000"`**
- **`"-200"`**
- **`"unknown"`**

**Expected result:**
- **`"$750"` → `750`**
- **`"1000"` → `1000`**
- **`"-200"` → `-200`**
- **`"unknown"` → `NaN`**

In [1695]:
df["bonus"] = df["bonus"].str.replace("$" ,"", regex=False)
df["bonus"] = df["bonus"].str.replace("," ,"" ,regex=False)
df["bonus"] = pd.to_numeric(df["bonus"], errors="coerce")
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,500.0,NaN,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,MARY JOHNSON,it,30.0,6000.0,NaN,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT Department,35.0,7500.5,NaN,2020-03-19 00:00:00,mary.brown@yahoo,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500.0,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,Human Resources,42.0,8000.0,NaN,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,mohammed hassan,sales,NaN,6500.0,-50.0,2020-10-23 00:00:00,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,500.0,2019-07-03,john.davishotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,SALES,NaN,NaN,NaN,2024-09-26 00:00:00,peter.wilson@company.com,55859430,NaN,active,1,1,0,0
8,E009,james miller,NaN,150.0,9000.0,NaN,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,6028 1693,FEMALE,active,0,0,0,0

# 🟡 LEVEL 3 — Data Types

## Task 13 — Convert Join Date

**Convert all valid dates into Pandas datetime.**

**Invalid values such as:**
```
invalid
2020/13/01
N/A
```

**should become:**
```
NaT
```

In [1696]:
df["join_date"] = pd.to_datetime(df["join_date"], errors="coerce", format="mixed", dayfirst=True)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,MARY JOHNSON,it,30.0,6000.0,NaN,2020-09-07,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT Department,35.0,7500.5,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500.0,2024-02-12,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,Human Resources,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,mohammed hassan,sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,500.0,2019-03-07,john.davishotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,SALES,NaN,NaN,NaN,2024-09-26,peter.wilson@company.com,55859430,NaN,active,1,1,0,0
8,E009,james miller,NaN,150.0,9000.0,NaN,2020-09-13,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,6028 1693,FEMALE,active,0,0,0,0

# 🟡 LEVEL 4 — Text Cleaning

## Task 14 — Standardize Names

**Convert names into proper case and remove multiple spaces between words.**

**Examples:**

**Expected result:**

- **`"JOHN SMITH"` → `"John Smith"`**
- **`"john smith"` → `"John Smith"`**
- **`"John Smith"` → `"John Smith"`**
- **`"mohammed  hassan"` → `"Mohammed Hassan"`**
- **`"Lisa   Thomas"` → `"Lisa Thomas"`**

In [1697]:
df["name"] = df["name"].str.title()
df["name"] = df["name"].str.replace(r"\s+", " ", regex=True)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,Mary Johnson,it,30.0,6000.0,NaN,2020-09-07,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT Department,35.0,7500.5,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500.0,2024-02-12,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,Human Resources,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,Mohammed Hassan,sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,500.0,2019-03-07,john.davishotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,SALES,NaN,NaN,NaN,2024-09-26,peter.wilson@company.com,55859430,NaN,active,1,1,0,0
8,E009,James Miller,NaN,150.0,9000.0,NaN,2020-09-13,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,6028 1693,FEMALE,active,0,0,0,0

# 🟡 LEVEL 4 — Text Cleaning

# Task 15 — Clean Department

**Standardize department names by fixing capitalization, extra spaces, and inconsistent department names.**

**Original Values and Expected Output:**

**Expected result:**

- **`"IT"` → `"IT"`**
- **`"it"` → `"IT"`**
- **`"IT Department"` → `"IT"`**
- **`"HR"` → `"HR"`**
- **`"Human Resources"` → `"HR"`**
- **`"Human Resource"` → `"HR"`**
- **`"sales"` → `"Sales"`**
- **`"Sales"` → `"Sales"`**
- **`"SALES"` → `"Sales"`**
- **`"Finance"` → `"Finance"`**
- **`"FINANCE"` → `"Finance"`**
- **`"finance"` → `"Finance"`**
- **`"Operations"` → `"Operations"`**
- **`"operations"` → `"Operations"`**
- **`"Marketing"` → `"Marketing"`**
- **`"marketing"` → `"Marketing"`**

In [1698]:
df["department"] = df["department"].str.lower()
department_clean = {
    "it" : "IT",
    "it department" : "IT",
    "hr" : "HR",
    "human resources" : "HR",
    "human resource" : "HR",
    "sales" : "Sales",
    "finance" : "Finance",
    "operations" : "Operations",
    "marketing" : "Marketing"
}

df["department"] = df["department"].map(department_clean)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,Mary Johnson,IT,30.0,6000.0,NaN,2020-09-07,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT,35.0,7500.5,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500.0,2024-02-12,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,500.0,2019-03-07,john.davishotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,Sales,NaN,NaN,NaN,2024-09-26,peter.wilson@company.com,55859430,NaN,active,1,1,0,0
8,E009,James Miller,NaN,150.0,9000.0,NaN,2020-09-13,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,6028 1693,FEMALE,active,0,0,0,0

# 🟡 LEVEL 4 — Text Cleaning

# Task 16 — Clean Gender

**Standardize gender values by converting inconsistent capitalization and abbreviations into consistent categories.**

**Expected result:**

- **`"Male"` → `"Male"`**
- **`"MALE"` → `"Male"`**
- **`"M"` → `"Male"`**
- **`"m"` → `"Male"`**
- **`"Female"` → `"Female"`**
- **`"F"` → `"Female"`**
- **`"female"` → `"Female"`**
- **`"other"` → `"Other"`**

In [1699]:
gnder_clean ={
    "male" : "Male",
    "m" : "Male",
    "female" : "Female",
    "f": "Female",
    "other" : "Other"
}

df["gender"] = df["gender"].str.lower()
df["gender"] = df["gender"].map(gnder_clean)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,NaN,0,0,0,0
1,E002,Mary Johnson,IT,30.0,6000.0,NaN,2020-09-07,joseph.yusuf@gmail.com,+974 7824 2882,Female,Active,0,0,0,0
2,E003,NaN,IT,35.0,7500.5,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500.0,2024-02-12,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,500.0,2019-03-07,john.davishotmail.com,not available,Female,active,0,0,0,0
7,E008,Lisa Thomas,Sales,NaN,NaN,NaN,2024-09-26,peter.wilson@company.com,55859430,NaN,active,1,1,0,0
8,E009,James Miller,NaN,150.0,9000.0,NaN,2020-09-13,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,6028 1693,Female,active,0,0,0,0

# 🟡 LEVEL 4 — Text Cleaning

## Task 17 — Clean Status

**Currently:**
- `Active`
- `active`
- `ACTIVE`
- `A`
- `Inactive`
- `inactive`
- `INACTIVE`
- `I`

**Objective:** Standardize status values into consistent categories.

**Expected result:**
- `Active`, `active`, `ACTIVE`, `A` → `Active`
- `Inactive`, `inactive`, `INACTIVE`, `I` → `Inactive`

In [1700]:
status_clean = {
    'active': "Active",
    'a' : "Active",
    'inactive' : "Inactive",
    'i' : "Inactive",
    'in active' : "Inactive"
}

df["status"] = df.status.str.lower()
df["status"] = df["status"].map(status_clean)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,NaN,0,0,0,0
1,E002,Mary Johnson,IT,30.0,6000.0,NaN,2020-09-07,joseph.yusuf@gmail.com,+974 7824 2882,Female,Active,0,0,0,0
2,E003,NaN,IT,35.0,7500.5,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,Active,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500.0,2024-02-12,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,+974 5995 1676,Male,Active,0,0,0,0
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,500.0,2019-03-07,john.davishotmail.com,not available,Female,Active,0,0,0,0
7,E008,Lisa Thomas,Sales,NaN,NaN,NaN,2024-09-26,peter.wilson@company.com,55859430,NaN,Active,1,1,0,0
8,E009,James Miller,NaN,150.0,9000.0,NaN,2020-09-13,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,6028 1693,Female,Active,0,0,0,0

# 🟡 LEVEL 5 — Email Cleaning

# Task 18 — Clean Email Whitespace

**Currently:**
- `" mary.johnson@gmail.com "`

**Objective:** **Remove leading and trailing whitespace from email addresses.**

**Expected result:**
- `"mary.johnson@gmail.com"`

In [1701]:
df["email"] = df["email"].str.strip()
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,NaN,0,0,0,0
1,E002,Mary Johnson,IT,30.0,6000.0,NaN,2020-09-07,joseph.yusuf@gmail.com,+974 7824 2882,Female,Active,0,0,0,0
2,E003,NaN,IT,35.0,7500.5,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,Active,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500.0,2024-02-12,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,+974 5995 1676,Male,Active,0,0,0,0
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,500.0,2019-03-07,john.davishotmail.com,not available,Female,Active,0,0,0,0
7,E008,Lisa Thomas,Sales,NaN,NaN,NaN,2024-09-26,peter.wilson@company.com,55859430,NaN,Active,1,1,0,0
8,E009,James Miller,NaN,150.0,9000.0,NaN,2020-09-13,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,6028 1693,Female,Active,0,0,0,0

# 🟡 LEVEL 5 — Email Cleaning

# Task 19 — Validate email addresses

**A valid email should roughly follow:**
```
something@domain.extension
```

**Identify invalid emails:**
```
sarakhan@gmail
james.miller@gmail
unknown
```
**Output column:** `email_valid`

**Do not delete them immediately**

In [1702]:
df["email_valid"] = df["email"].str.match(r"^[a-zA-Z0-9-.%+_]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$")
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing,email_valid
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,NaN,0,0,0,0,True
1,E002,Mary Johnson,IT,30.0,6000.0,NaN,2020-09-07,joseph.yusuf@gmail.com,+974 7824 2882,Female,Active,0,0,0,0,True
2,E003,NaN,IT,35.0,7500.5,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,Active,0,0,0,0,False
3,E004,Sara Khan,HR,NaN,NaN,500.0,2024-02-12,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0,True
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,+974 5995 1676,Male,Active,0,0,0,0,True
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0,True
6,E007,David Wilson,Sales,29.0,7200.0,500.0,2019-03-07,john.davishotmail.com,not available,Female,Active,0,0,0,0,False
7,E008,Lisa Thomas,Sales,NaN,NaN,NaN,2024-09-26,peter.wilson@company.com,55859430,NaN,Active,1,1,0,0,True
8,E009,James Miller,NaN,150.0,9000.0,NaN,2020-09-13,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0,True
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,6028 1693,Female,Active,0,0,0,0,True

# 🟡 LEVEL 5 — Email Cleaning

## Task 20 — Extract Email Domain

**Objective: Extract the domain from each email address and store it in a new column named** `email_domain`.

**Currently:**
- `john.smith@gmail.com`

**Expected result:**
- `gmail.com`
- `yahoo.com`
- `company.com`

**Output column:** `email_domain`

In [1703]:
df["email_domain"] = df["email"].str.extract(r"@(.+)")
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing,email_valid,email_domain
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,NaN,0,0,0,0,True,hotmail.com
1,E002,Mary Johnson,IT,30.0,6000.0,NaN,2020-09-07,joseph.yusuf@gmail.com,+974 7824 2882,Female,Active,0,0,0,0,True,gmail.com
2,E003,NaN,IT,35.0,7500.5,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,Active,0,0,0,0,False,yahoo
3,E004,Sara Khan,HR,NaN,NaN,500.0,2024-02-12,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0,True,yahoo.com
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,+974 5995 1676,Male,Active,0,0,0,0,True,hotmail.com
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0,True,yahoo.com
6,E007,David Wilson,Sales,29.0,7200.0,500.0,2019-03-07,john.davishotmail.com,not available,Female,Active,0,0,0,0,False,NaN
7,E008,Lisa Thomas,Sales,NaN,NaN,NaN,2024-09-26,peter.wilson@company.com,55859430,NaN,Active,1,1,0,0,True,company.com
8,E009,James Miller,NaN,150.0,9000.0,NaN,2020-09-13,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0,True,yahoo.com
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,6028 1693,Female,Active,0,0,0,0,True,yahoo.com

# 🟠 LEVEL 6 — Phone Cleaning

# Task 21 — Remove Phone Formatting

**Objective:  Remove spaces, hyphens, and other non-digit characters from phone numbers.**

**Currently:**
- `+974 5555 1111`
- `974-5555-2222`
- `974 5555 5555`
- `+974-5555-8888`

**Expected result:**
- `97455551111`
- `97455552222`
- `97455555555`
- `97455558888`

In [1704]:
df["phone"] = df["phone"].str.replace(r"\D","", regex=True)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing,email_valid,email_domain
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,NaN,0,0,0,0,True,hotmail.com
1,E002,Mary Johnson,IT,30.0,6000.0,NaN,2020-09-07,joseph.yusuf@gmail.com,97478242882,Female,Active,0,0,0,0,True,gmail.com
2,E003,NaN,IT,35.0,7500.5,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,Active,0,0,0,0,False,yahoo
3,E004,Sara Khan,HR,NaN,NaN,500.0,2024-02-12,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0,True,yahoo.com
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,97459951676,Male,Active,0,0,0,0,True,hotmail.com
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,60281693,Male,Inactive,0,0,0,0,True,yahoo.com
6,E007,David Wilson,Sales,29.0,7200.0,500.0,2019-03-07,john.davishotmail.com,,Female,Active,0,0,0,0,False,NaN
7,E008,Lisa Thomas,Sales,NaN,NaN,NaN,2024-09-26,peter.wilson@company.com,55859430,NaN,Active,1,1,0,0,True,company.com
8,E009,James Miller,NaN,150.0,9000.0,NaN,2020-09-13,zainab.martin@yahoo.com,97433138535,NaN,NaN,0,0,0,0,True,yahoo.com
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,60281693,Female,Active,0,0,0,0,True,yahoo.com

# 🟠 LEVEL 6 — Phone Cleaning

# Task 22 — Standardize Qatar Phone Numbers

**Objective: Standardize Qatar phone numbers into the format `974XXXXXXXX`, where appropriate.**

**Expected format:**
- `974` followed by exactly 8 digits.

**Tasks:**
- Identify phone numbers that match the expected pattern.
- Identify phone numbers that do not match the expected pattern.
- Create a new column named `phone_valid`.

**Expected result:**
- `97455551111` → `True`
- `9745555222` → `False`
- `12345678901` → `False`

**Important: Do not delete invalid phone numbers immediately.**

In [1705]:
df["phone_valid"] = df["phone"].str.fullmatch(r"974\d{8}", na=False)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing,email_valid,email_domain,phone_valid
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,NaN,0,0,0,0,True,hotmail.com,True
1,E002,Mary Johnson,IT,30.0,6000.0,NaN,2020-09-07,joseph.yusuf@gmail.com,97478242882,Female,Active,0,0,0,0,True,gmail.com,True
2,E003,NaN,IT,35.0,7500.5,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,Active,0,0,0,0,False,yahoo,False
3,E004,Sara Khan,HR,NaN,NaN,500.0,2024-02-12,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0,True,yahoo.com,False
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,97459951676,Male,Active,0,0,0,0,True,hotmail.com,True
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,60281693,Male,Inactive,0,0,0,0,True,yahoo.com,False
6,E007,David Wilson,Sales,29.0,7200.0,500.0,2019-03-07,john.davishotmail.com,,Female,Active,0,0,0,0,False,NaN,False
7,E008,Lisa Thomas,Sales,NaN,NaN,NaN,2024-09-26,peter.wilson@company.com,55859430,NaN,Active,1,1,0,0,True,company.com,False
8,E009,James Miller,NaN,150.0,9000.0,NaN,2020-09-13,zainab.martin@yahoo.com,97433138535,NaN,NaN,0,0,0,0,True,yahoo.com,True
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,60281693,Female,Active,0,0,0,0,True,yahoo.com,False

# 🟠 LEVEL 7 — Numeric Validation

# Task 23 — Find Invalid Ages

**Objective: Identify employee ages that fall outside the valid range.**

**Valid age range:** 18–65 (inclusive)

**Examples of invalid ages:**
- `150`
- `-5`

**Task: 
Create a new column named `age_valid` to indicate whether each employee's age is within the valid range.**

**Expected result:**
- `150` → `False`
- `-5` → `False`
- `25` → `True`

**Important: Identify invalid ages without deleting them immediately.**

In [1706]:
df["age_valid"] = df["age"].between(18,65, inclusive="both")
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing,email_valid,email_domain,phone_valid,age_valid
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,NaN,0,0,0,0,True,hotmail.com,True,True
1,E002,Mary Johnson,IT,30.0,6000.0,NaN,2020-09-07,joseph.yusuf@gmail.com,97478242882,Female,Active,0,0,0,0,True,gmail.com,True,True
2,E003,NaN,IT,35.0,7500.5,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,Active,0,0,0,0,False,yahoo,False,True
3,E004,Sara Khan,HR,NaN,NaN,500.0,2024-02-12,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0,True,yahoo.com,False,False
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,97459951676,Male,Active,0,0,0,0,True,hotmail.com,True,True
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,60281693,Male,Inactive,0,0,0,0,True,yahoo.com,False,False
6,E007,David Wilson,Sales,29.0,7200.0,500.0,2019-03-07,john.davishotmail.com,,Female,Active,0,0,0,0,False,NaN,False,True
7,E008,Lisa Thomas,Sales,NaN,NaN,NaN,2024-09-26,peter.wilson@company.com,55859430,NaN,Active,1,1,0,0,True,company.com,False,False
8,E009,James Miller,NaN,150.0,9000.0,NaN,2020-09-13,zainab.martin@yahoo.com,97433138535,NaN,NaN,0,0,0,0,True,yahoo.com,True,False
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,60281693,Female,Active,0,0,0,0,True,yahoo.com,False,False

# 🟠 LEVEL 7 — Numeric Validation

# Task 24 — Find Invalid Salaries

**Objective:  Identify salaries that do not meet the valid salary condition.**

**Valid salary condition:  Salary must be greater than `0`.**

**Example of an invalid salary:**
- `-5000`

**Task:
Create a new column named `salary_valid` to indicate whether each salary is valid.**

**Expected result:**
- `-5000` → `False`
- `5000` → `True`
- `0` → `False`

**Important:  Identify invalid salaries without deleting or modifying the original values.**

In [1707]:
df["salary_valid"] = df["salary"] > 0
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing,email_valid,email_domain,phone_valid,age_valid,salary_valid
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,NaN,0,0,0,0,True,hotmail.com,True,True,True
1,E002,Mary Johnson,IT,30.0,6000.0,NaN,2020-09-07,joseph.yusuf@gmail.com,97478242882,Female,Active,0,0,0,0,True,gmail.com,True,True,True
2,E003,NaN,IT,35.0,7500.5,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,Active,0,0,0,0,False,yahoo,False,True,True
3,E004,Sara Khan,HR,NaN,NaN,500.0,2024-02-12,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0,True,yahoo.com,False,False,False
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,97459951676,Male,Active,0,0,0,0,True,hotmail.com,True,True,True
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,60281693,Male,Inactive,0,0,0,0,True,yahoo.com,False,False,True
6,E007,David Wilson,Sales,29.0,7200.0,500.0,2019-03-07,john.davishotmail.com,,Female,Active,0,0,0,0,False,NaN,False,True,True
7,E008,Lisa Thomas,Sales,NaN,NaN,NaN,2024-09-26,peter.wilson@company.com,55859430,NaN,Active,1,1,0,0,True,company.com,False,False,False
8,E009,James Miller,NaN,150.0,9000.0,NaN,2020-09-13,zainab.martin@yahoo.com,97433138535,NaN,NaN,0,0,0,0,True,yahoo.com,True,False,True
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,60281693,Female,Active,0,0,0,0,True,yahoo.com,False,False,False

# 🟠 LEVEL 7 — Numeric Validation

# Task 25 — Find Invalid Bonuses

**Objective:   Identify bonus values that do not meet the valid bonus condition.**

**Valid bonus condition:    Bonus must be greater than or equal to `0`.**

**Example of an invalid bonus:**
- `-200`

**Task:
Create a new column named `bonus_valid` to indicate whether each bonus is valid.**

**Expected result:**
- `-200` → `False`
- `500` → `True`
- `0` → `True`

**Important:   Identify invalid bonuses without deleting or modifying the original values.**

In [1708]:
df["bonus_valid"] = df["bonus"] >=0
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,...,age_missing,salary_missing,email_missing,phone_missing,email_valid,email_domain,phone_valid,age_valid,salary_valid,bonus_valid
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,...,0,0,0,0,True,hotmail.com,True,True,True,True
1,E002,Mary Johnson,IT,30.0,6000.0,NaN,2020-09-07,joseph.yusuf@gmail.com,97478242882,Female,...,0,0,0,0,True,gmail.com,True,True,True,False
2,E003,NaN,IT,35.0,7500.5,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,...,0,0,0,0,False,yahoo,False,True,True,False
3,E004,Sara Khan,HR,NaN,NaN,500.0,2024-02-12,daniel.johnson@yahoo.com,37855874,Female,...,1,1,0,0,True,yahoo.com,False,False,False,True
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,97459951676,Male,...,0,0,0,0,True,hotmail.com,True,True,True,False
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,60281693,Male,...,0,0,0,0,True,yahoo.com,False,False,True,False
6,E007,David Wilson,Sales,29.0,7200.0,500.0,2019-03-07,john.davishotmail.com,,Female,...,0,0,0,0,False,NaN,False,True,True,True
7,E008,Lisa Thomas,Sales,NaN,NaN,NaN,2024-09-26,peter.wilson@company.com,55859430,NaN,...,1,1,0,0,True,company.com,False,False,False,False
8,E009,James Miller,NaN,150.0,9000.0,NaN,2020-09-13,zainab.martin@yahoo.com,97433138535,NaN,...,0,0,0,0,True,yahoo.com,True,False,True,False
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,60281693,Female,...,0,0,0,0,True,yahoo.com,False,False,False,True

# 🟠 LEVEL 8 — Outlier Detection

# Task 26 — Detect Salary Outliers

**Objective:   Identify unusually low or high salaries using the Interquartile Range (IQR) method.**

**Approach:**
1. Calculate the first quartile (`Q1`) using the 25th percentile.
2. Calculate the third quartile (`Q3`) using the 75th percentile.
3. Calculate the IQR.
4. Calculate the lower and upper outlier boundaries.
5. Create a new column named `salary_outlier` to identify potential outliers.

**Formulas:**
- `IQR = Q3 - Q1`
- `Lower Boundary = Q1 - (1.5 × IQR)`
- `Upper Boundary = Q3 + (1.5 × IQR)`

**Expected result:**
- `True` — salary is below the lower boundary or above the upper boundary.
- `False` — salary is within the boundaries.

**Important:   Identify potential outliers without immediately deleting or modifying the original salary values.**

In [1709]:
Q1 = df["salary"].quantile(0.25)
Q3 = df["salary"].quantile(0.75)
IQR = Q3-Q1
lower = Q1 - (1.5 * IQR)
upper = Q3 + (1.5 * IQR)
df["salary_outlier"] = ((df["salary"] < lower) | (df["salary"] > upper)).where(df["salary"].notna(), np.nan)
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower boundary:", lower)
print("Upper boundary:", upper)
df.head(10)

Q1: 5250.0
Q3: 7500.0
IQR: 2250.0
Lower boundary: 1875.0
Upper boundary: 10875.0

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,...,salary_missing,email_missing,phone_missing,email_valid,email_domain,phone_valid,age_valid,salary_valid,bonus_valid,salary_outlier
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,...,0,0,0,True,hotmail.com,True,True,True,True,False
1,E002,Mary Johnson,IT,30.0,6000.0,NaN,2020-09-07,joseph.yusuf@gmail.com,97478242882,Female,...,0,0,0,True,gmail.com,True,True,True,False,False
2,E003,NaN,IT,35.0,7500.5,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,...,0,0,0,False,yahoo,False,True,True,False,False
3,E004,Sara Khan,HR,NaN,NaN,500.0,2024-02-12,daniel.johnson@yahoo.com,37855874,Female,...,1,0,0,True,yahoo.com,False,False,False,True,NaN
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,97459951676,Male,...,0,0,0,True,hotmail.com,True,True,True,False,False
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,60281693,Male,...,0,0,0,True,yahoo.com,False,False,True,False,False
6,E007,David Wilson,Sales,29.0,7200.0,500.0,2019-03-07,john.davishotmail.com,,Female,...,0,0,0,False,NaN,False,True,True,True,False
7,E008,Lisa Thomas,Sales,NaN,NaN,NaN,2024-09-26,peter.wilson@company.com,55859430,NaN,...,1,0,0,True,company.com,False,False,False,False,NaN
8,E009,James Miller,NaN,150.0,9000.0,NaN,2020-09-13,zainab.martin@yahoo.com,97433138535,NaN,...,0,0,0,True,yahoo.com,True,False,True,False,False
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,60281693,Female,...,0,0,0,True,yahoo.com,False,False,False,True,True

# 🟠 LEVEL 8 — Outlier Detection

# Task 27 — Detect Age Outliers

**Objective:   Identify unusually low or high employee ages using the Interquartile Range (IQR) method.**

**Approach:**
1. Calculate the first quartile (`Q1`) using the 25th percentile.
2. Calculate the third quartile (`Q3`) using the 75th percentile.
3. Calculate the IQR.
4. Calculate the lower and upper outlier boundaries.
5. Create a new column named `age_outlier` to identify potential outliers.

**Formulas:**
- `IQR = Q3 - Q1`
- `Lower Boundary = Q1 - (1.5 × IQR)`
- `Upper Boundary = Q3 + (1.5 × IQR)`

**Expected result:**
- `True` — age is below the lower boundary or above the upper boundary.
- `False` — age is within the boundaries.

**Important:   Identify potential outliers without immediately deleting or modifying the original age values.**

In [1710]:
Q1 = df["age"].quantile(0.25)
Q3 = df["age"].quantile(0.75)
IQR = Q3-Q1
lower = Q1 - (1.5 * IQR)
upper = Q3 + (1.5 * IQR)
df["age_outlier"] = ((df["age"] < lower) | (df["age"] > upper)).where(df["age"].notna(), np.nan)
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower boundary:", lower)
print("Upper boundary:", upper)

df.head(10)

Q1: 26.0
Q3: 41.0
IQR: 15.0
Lower boundary: 3.5
Upper boundary: 63.5

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,...,email_missing,phone_missing,email_valid,email_domain,phone_valid,age_valid,salary_valid,bonus_valid,salary_outlier,age_outlier
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,...,0,0,True,hotmail.com,True,True,True,True,False,False
1,E002,Mary Johnson,IT,30.0,6000.0,NaN,2020-09-07,joseph.yusuf@gmail.com,97478242882,Female,...,0,0,True,gmail.com,True,True,True,False,False,False
2,E003,NaN,IT,35.0,7500.5,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,...,0,0,False,yahoo,False,True,True,False,False,False
3,E004,Sara Khan,HR,NaN,NaN,500.0,2024-02-12,daniel.johnson@yahoo.com,37855874,Female,...,0,0,True,yahoo.com,False,False,False,True,NaN,NaN
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,97459951676,Male,...,0,0,True,hotmail.com,True,True,True,False,False,False
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,60281693,Male,...,0,0,True,yahoo.com,False,False,True,False,False,NaN
6,E007,David Wilson,Sales,29.0,7200.0,500.0,2019-03-07,john.davishotmail.com,,Female,...,0,0,False,NaN,False,True,True,True,False,False
7,E008,Lisa Thomas,Sales,NaN,NaN,NaN,2024-09-26,peter.wilson@company.com,55859430,NaN,...,0,0,True,company.com,False,False,False,False,NaN,NaN
8,E009,James Miller,NaN,150.0,9000.0,NaN,2020-09-13,zainab.martin@yahoo.com,97433138535,NaN,...,0,0,True,yahoo.com,True,False,True,False,False,True
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,60281693,Female,...,0,0,True,yahoo.com,False,False,False,True,True,True

# 🔴 LEVEL 9 — Duplicate Cleaning

# Task 28 — Find Duplicate Rows

**Objective:  Identify duplicate rows in the dataset.**

**Method:**
- Use `df.duplicated()` to check whether each row duplicates a previous row.
- Returns `True` for duplicate rows and `False` for non-duplicate rows.

**Task:**
- Identify duplicate rows without deleting them immediately.
- Review the results before deciding how to handle duplicates.

**Important:   By default, `df.duplicated()` considers all columns when checking for duplicate rows and marks the first occurrence as `False`.**

In [1711]:
check_duplicate = df.duplicated()
check_duplicate

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499     True
Length: 500, dtype: bool

# 🔴 LEVEL 9 — Duplicate Cleaning

# Task 29 — Find Duplicate Employee IDs

**Objective:  Identify duplicate employee IDs in the dataset.**

**Column Checked:** `employee_id`

**Task:**
- Check the `employee_id` column for duplicate values.
- Identify employee IDs that appear more than once.

**Expected Result:**
- `E015` and `E500` appears more than once in the dataset.
- Duplicate employee IDs are identified without deleting any records.

In [1712]:
duplicate_employee_id = df[df.duplicated(subset="employee_id", keep=False)]
duplicate_employee_id

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,...,email_missing,phone_missing,email_valid,email_domain,phone_valid,age_valid,salary_valid,bonus_valid,salary_outlier,age_outlier
14,E015,Daniel Wilson,IT,40.0,7000.0,-50.0,2019-10-14,lisa.ahmed@hotmail.com,97445192493,Male,...,0,0,True,hotmail.com,True,True,True,False,False,False
15,E015,Aisha Khan,IT,33.0,6500.0,NaN,2022-07-02,adam.thomas@hotmail.com,97472545481,NaN,...,0,0,True,hotmail.com,True,True,True,False,False,False
498,E500,Hana Davis,Operations,38.0,6200.0,NaN,2023-10-16,john..smith@gmail.com,97474685012,Male,...,0,0,True,gmail.com,True,True,True,False,False,False
499,E500,Hana Davis,Operations,38.0,6200.0,NaN,2023-10-16,john..smith@gmail.com,97474685012,Male,...,0,0,True,gmail.com,True,True,True,False,False,False

# 🔴 LEVEL 9 — Duplicate Cleaning

# Task 30 — Remove Exact Duplicate Rows

**Objective:   Remove exact duplicate rows while preserving records that require further investigation.**

**Approach:**
- Counted the exact duplicate rows using `df.duplicated().sum()`.
- Displayed all rows involved in duplication using `df.duplicated(keep=False)`.
- Used `df.drop_duplicates()` to remove exact duplicate rows.
- Rechecked the dataset to confirm that no exact duplicate rows remained.

**Results:**
- Exact duplicate occurrences before cleaning: **1**
- Rows involved in the duplication: **2**
- Exact duplicate occurrences after cleaning: **0**

**Duplicate Employee ID Investigation:**
- `E500`: The two records had identical details, so one duplicate record was removed.
- `E015`: The records had different details, so both were retained for further investigation.

**Conclusion:   Exact duplicate rows were removed successfully. Records with duplicate employee IDs were not automatically deleted; they were reviewed based on their details.**

In [1713]:
number_of_exact_duplicate = df.duplicated().sum()
exact_duplicate_rows = df[df.duplicated(keep=False)]
print("Number of exact duplicate :" , number_of_exact_duplicate)
exact_duplicate_rows

Number of exact duplicate : 1

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,...,email_missing,phone_missing,email_valid,email_domain,phone_valid,age_valid,salary_valid,bonus_valid,salary_outlier,age_outlier
498,E500,Hana Davis,Operations,38.0,6200.0,NaN,2023-10-16,john..smith@gmail.com,97474685012,Male,...,0,0,True,gmail.com,True,True,True,False,False,False
499,E500,Hana Davis,Operations,38.0,6200.0,NaN,2023-10-16,john..smith@gmail.com,97474685012,Male,...,0,0,True,gmail.com,True,True,True,False,False,False

In [ ]:
df = df.drop_duplicates()
number_of_exact_duplicate = df.duplicated().sum()
print("Number of exact duplicate :" , number_of_exact_duplicate)

Number of exact duplicate : 0