# Pandas Data Cleaning Project

In [183]:
import pandas as pd
import numpy as np
df = pd.read_excel(r"D:\Private\555 sha\P\pandas-data-cleaning-project\data\raw_data.xlsx",keep_default_na=False, dtype="str")

# 🟢 LEVEL 1 — Basic Structural Cleaning

## Task 1 — Inspect the Dataset

**Find:**
- **Number of rows**
- **Number of columns**
- **Column names**
- **Data types**
- **Memory usage**
- **First 5 rows**
- **Last 5 rows**

In [184]:
df.shape

(500, 11)

In [185]:
df.columns

Index([' Employee ID ', 'NAME', 'Department', 'Age', 'Salary', 'Bonus',
       'Join Date', 'Email', 'Phone', 'Gender', 'Status'],
      dtype='str')

In [186]:
df.dtypes

 Employee ID     str
NAME             str
Department       str
Age              str
Salary           str
Bonus            str
Join Date        str
Email            str
Phone            str
Gender           str
Status           str
dtype: object

In [187]:
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0    Employee ID   500 non-null    str
 1   NAME           500 non-null    str
 2   Department     500 non-null    str
 3   Age            500 non-null    str
 4   Salary         500 non-null    str
 5   Bonus          500 non-null    str
 6   Join Date      500 non-null    str
 7   Email          500 non-null    str
 8   Phone          500 non-null    str
 9   Gender         500 non-null    str
 10  Status         500 non-null    str
dtypes: str(11)
memory usage: 307.0 KB

In [188]:
df.head(5)

,Employee ID,NAME,Department,Age,Salary,Bonus,Join Date,Email,Phone,Gender,Status
0,E001,John Smith,IT,25,5000,500,unknown,noor.martin@hotmail.com,97474793157,M,N/A
1,E002,MARY JOHNSON,it,30,6000,null,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active
2,E003,,IT Department,35,7500.5,?,2020-03-19 00:00:00,mary.brown@yahoo.com,37773911,Female,A
3,E004,Sara Khan,HR,N/A,N/A,500,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive
4,E005,Robert Brown,Human Resources,42,8000,Unknown,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active

In [189]:
df.tail(5)

,Employee ID,NAME,Department,Age,Salary,Bonus,Join Date,Email,Phone,Gender,Status
495,E496,Daniel Smith,Sales,45,unknown,-50,2019-02-09 00:00:00,emma.taylor@company.com,31753140,Female,ACTIVE
496,E497,Maya Ali,IT Department,32,4800,1000,2020-02-18,ryan.taylor@hotmail.com,974-5587-2645,m,ACTIVE
497,E498,Unknown,Marketing,27,N/A,300,2020-12-15 00:00:00,amira.moore@gmail.com,974-6740-1535,female,Inactive
498,E500,Peter Khan,HR,-8,7000,not available,December 15 2019,joseph.brown@hotmail.com,-9530,M,unknown
499,E500,Hana Davis,Operations,38,6200,,16-10-2023,john..smith@gmail.com,974-7468-5012,male,INACTIVE

# 🟢 LEVEL 1 — Basic Structural Cleaning

## Task 2 — Clean Column Names

**Convert column names into lowercase, remove extra spaces, and replace spaces between words with underscores.**

**Example:**
- `" Employee ID "` → `employee_id`
- `"NAME"` → `name`
- `"Department"` → `department`
- `"Join Date"` → `join_date`

In [190]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(r"\s+","_", regex=True)
df.columns

Index(['employee_id', 'name', 'department', 'age', 'salary', 'bonus',
       'join_date', 'email', 'phone', 'gender', 'status'],
      dtype='str')

# 🟢 LEVEL 1 — Basic Structural Cleaning

## Task 3 — Remove Leading and Trailing Whitespace

**Clean leading and trailing whitespace from all string columns.**

**Examples:**
- `"     John Smith     "` → `"John Smith"`
- `"it          "` → `"it"`
- `"    2022-05-20     "` → `"2022-05-20"`

In [191]:
for cl in df.select_dtypes(include="str").columns :
    df[cl] = df[cl].str.strip()
    df[cl] = df[cl].str.replace(r"\s+", " ", regex = True)    
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status
0,E001,John Smith,IT,25,5000,500,unknown,noor.martin@hotmail.com,97474793157,M,N/A
1,E002,MARY JOHNSON,it,30,6000,null,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active
2,E003,,IT Department,35,7500.5,?,2020-03-19 00:00:00,mary.brown@yahoo.com,37773911,Female,A
3,E004,Sara Khan,HR,N/A,N/A,500,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive
4,E005,Robert Brown,Human Resources,42,8000,Unknown,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active
5,E006,mohammed hassan,sales,twenty-eight,6500,-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,6028 1693,Male,Inactive
6,E007,David Wilson,Sales,29,7200,500,2019-07-03,john.davis@hotmail.com,not available,f,active
7,E008,Lisa Thomas,SALES,,,null,2024-09-26 00:00:00,peter.wilson@company.com,55859430,unknown,active
8,E009,james miller,,150,9000,,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,,
9,E010,Emma Davis,Finance,-5,-5000,500,2020-05-19,adam.anderson@yahoo.com,-10045,FEMALE,active

# 🟢 LEVEL 1 — Basic Structural Cleaning

## Task 4 — Find Completely Empty Strings

- **Find cells containing empty strings (`""`) or strings with only whitespace (`"   "`).**
- **Replace them with `NaN`.**

In [192]:
for cl in df.columns:
    df[cl] = df[cl].replace(r"^\s*$", np.nan, regex=True)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status
0,E001,John Smith,IT,25,5000,500,unknown,noor.martin@hotmail.com,97474793157,M,N/A
1,E002,MARY JOHNSON,it,30,6000,null,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active
2,E003,NaN,IT Department,35,7500.5,?,2020-03-19 00:00:00,mary.brown@yahoo.com,37773911,Female,A
3,E004,Sara Khan,HR,N/A,N/A,500,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive
4,E005,Robert Brown,Human Resources,42,8000,Unknown,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active
5,E006,mohammed hassan,sales,twenty-eight,6500,-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,6028 1693,Male,Inactive
6,E007,David Wilson,Sales,29,7200,500,2019-07-03,john.davis@hotmail.com,not available,f,active
7,E008,Lisa Thomas,SALES,NaN,NaN,null,2024-09-26 00:00:00,peter.wilson@company.com,55859430,unknown,active
8,E009,james miller,NaN,150,9000,NaN,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN
9,E010,Emma Davis,Finance,-5,-5000,500,2020-05-19,adam.anderson@yahoo.com,-10045,FEMALE,active

# 🟢 LEVEL 2 — Missing Values

## Task 5 — Identify Missing Values

- **Identify missing values using `df.isna()`.**
- **Calculate the missing value count for every column.**

In [193]:
missing_values = df.isna().sum()
missing_values

employee_id     0
name            1
department      1
age             1
salary          1
bonus          37
join_date       7
email           8
phone           4
gender         27
status         26
dtype: int64

# 🟢 LEVEL 2 — Missing Values

## Task 6 — Calculate Missing Percentage

- **Calculate the missing value count for every column.**
- **Calculate the missing percentage for every column.**

In [194]:
missing_percentage = df.isna().mean() * 100.0
result = pd.DataFrame({
    "missing_count" : missing_values,
    "missing_percentage" : missing_percentage
})
result = result.reset_index(names="Column")
result

         Column  missing_count  missing_percentage
0   employee_id              0                 0.0
1          name              1                 0.2
2    department              1                 0.2
3           age              1                 0.2
4        salary              1                 0.2
5         bonus             37                 7.4
6     join_date              7                 1.4
7         email              8                 1.6
8         phone              4                 0.8
9        gender             27                 5.4
10       status             26                 5.2

# 🟢 LEVEL 2 — Missing Values

## Task 7 — Replace Fake Missing Values

**Convert the following fake missing values into actual `NaN`:**

- **`"N/A"`**
- **`"NULL"`**
- **`"unknown"`**
- **`"Unknown"`**
- **`""`** (empty string)

In [195]:
fake_missing = ["N/A","NULL","unknown","Unknown","", "null"]
for cl in df.columns:
    df[cl] = df[cl].replace(fake_missing,np.nan)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status
0,E001,John Smith,IT,25,5000,500,NaN,noor.martin@hotmail.com,97474793157,M,NaN
1,E002,MARY JOHNSON,it,30,6000,NaN,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active
2,E003,NaN,IT Department,35,7500.5,?,2020-03-19 00:00:00,mary.brown@yahoo.com,37773911,Female,A
3,E004,Sara Khan,HR,NaN,NaN,500,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive
4,E005,Robert Brown,Human Resources,42,8000,NaN,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active
5,E006,mohammed hassan,sales,twenty-eight,6500,-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,6028 1693,Male,Inactive
6,E007,David Wilson,Sales,29,7200,500,2019-07-03,john.davis@hotmail.com,not available,f,active
7,E008,Lisa Thomas,SALES,NaN,NaN,NaN,2024-09-26 00:00:00,peter.wilson@company.com,55859430,NaN,active
8,E009,james miller,NaN,150,9000,NaN,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN
9,E010,Emma Davis,Finance,-5,-5000,500,2020-05-19,adam.anderson@yahoo.com,-10045,FEMALE,active

## 🟢 LEVEL 2 — Missing Values

# Task 8 — Decide How to Handle Missing Values

**Missing-value treatment will be performed after completing the data-cleaning and data-type conversion tasks to avoid affecting subsequent analysis.**

**The appropriate strategy will be selected based on each column's meaning and the amount of missing data.**

## Task 9 — Create Missing Indicators

**Create the following columns:**
- **`age_missing`**
- **`salary_missing`**
- **`email_missing`**
- **`phone_missing`**

**Example:**
- **`age = NaN` → `age_missing = 1`**
- **`age = 25` → `age_missing = 0`**

In [196]:
missing_columns = ['age','salary','email','phone']
for cl in missing_columns:
    df[cl+"_missing"] = df[cl].isna().astype("int")
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25,5000,500,NaN,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,MARY JOHNSON,it,30,6000,NaN,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT Department,35,7500.5,?,2020-03-19 00:00:00,mary.brown@yahoo.com,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,Human Resources,42,8000,NaN,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,mohammed hassan,sales,twenty-eight,6500,-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29,7200,500,2019-07-03,john.davis@hotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,SALES,NaN,NaN,NaN,2024-09-26 00:00:00,peter.wilson@company.com,55859430,NaN,active,1,1,0,0
8,E009,james miller,NaN,150,9000,NaN,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5,-5000,500,2020-05-19,adam.anderson@yahoo.com,-10045,FEMALE,active,0,0,0,0

# 🟡 LEVEL 3 — Data Types

## Task 10 — Convert Age
**Currently:**
- **`"25"`**
- **`" 30 "`**
- **`"35"`**
- **`"twenty-eight"`**
- **`"N/A"`**
**Objective: Convert `age` into numeric values.**
**Expected result: Invalid values should become `NaN`**

In [197]:
df["age"] = pd.to_numeric(df["age"], errors="coerce")
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000,500,NaN,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,MARY JOHNSON,it,30.0,6000,NaN,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT Department,35.0,7500.5,?,2020-03-19 00:00:00,mary.brown@yahoo.com,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,Human Resources,42.0,8000,NaN,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,mohammed hassan,sales,NaN,6500,-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200,500,2019-07-03,john.davis@hotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,SALES,NaN,NaN,NaN,2024-09-26 00:00:00,peter.wilson@company.com,55859430,NaN,active,1,1,0,0
8,E009,james miller,NaN,150.0,9000,NaN,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000,500,2020-05-19,adam.anderson@yahoo.com,-10045,FEMALE,active,0,0,0,0

# 🟡 LEVEL 3 — Data Types

## Task 11 — Convert Salary

**Currently:**
- **`"$5,000"`**
- **`"6000"`**
- **`"7,500.50"`**
- **`"8,000"`**

**Objective: Remove currency symbols and commas, then convert `salary` into numeric values.**

**Expected result:**
- **`5000`**
- **`6000`**
- **`7500.50`**
- **`8000`**

In [198]:
df["salary"] = df["salary"].str.replace('$',"", regex=False)
df["salary"] = df["salary"].str.replace(',',"", regex=False)
df["salary"] = pd.to_numeric(df["salary"], errors="coerce")
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,500,NaN,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,MARY JOHNSON,it,30.0,6000.0,NaN,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT Department,35.0,7500.5,?,2020-03-19 00:00:00,mary.brown@yahoo.com,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,Human Resources,42.0,8000.0,NaN,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,mohammed hassan,sales,NaN,6500.0,-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,500,2019-07-03,john.davis@hotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,SALES,NaN,NaN,NaN,2024-09-26 00:00:00,peter.wilson@company.com,55859430,NaN,active,1,1,0,0
8,E009,james miller,NaN,150.0,9000.0,NaN,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500,2020-05-19,adam.anderson@yahoo.com,-10045,FEMALE,active,0,0,0,0

# 🟡 LEVEL 3 — Data Types

## Task 12 — Convert Bonus to Numeric

**Clean the `bonus` column and convert it to a numeric data type.**

**Example values:**
- **`"$750"`**
- **`"1000"`**
- **`"-200"`**
- **`"unknown"`**

**Expected result:**
- **`"$750"` → `750`**
- **`"1000"` → `1000`**
- **`"-200"` → `-200`**
- **`"unknown"` → `NaN`**

In [199]:
df["bonus"] = df["bonus"].str.replace("$" ,"", regex=False)
df["bonus"] = df["bonus"].str.replace("," ,"" ,regex=False)
df["bonus"] = pd.to_numeric(df["bonus"], errors="coerce")
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,500.0,NaN,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,MARY JOHNSON,it,30.0,6000.0,NaN,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT Department,35.0,7500.5,NaN,2020-03-19 00:00:00,mary.brown@yahoo.com,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500.0,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,Human Resources,42.0,8000.0,NaN,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,mohammed hassan,sales,NaN,6500.0,-50.0,2020-10-23 00:00:00,aisha.johnson@yahoo.com,6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,500.0,2019-07-03,john.davis@hotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,SALES,NaN,NaN,NaN,2024-09-26 00:00:00,peter.wilson@company.com,55859430,NaN,active,1,1,0,0
8,E009,james miller,NaN,150.0,9000.0,NaN,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,-10045,FEMALE,active,0,0,0,0

# 🟡 LEVEL 3 — Data Types

## Task 13 — Convert Join Date

**Convert all valid dates into Pandas datetime.**

**Invalid values such as:**
```
invalid
2020/13/01
N/A
```

**should become:**
```
NaT
```

In [200]:
df["join_date"] = pd.to_datetime(df["join_date"], errors="coerce", format="mixed", dayfirst=True)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,MARY JOHNSON,it,30.0,6000.0,NaN,2020-09-07,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT Department,35.0,7500.5,NaN,2020-03-19,mary.brown@yahoo.com,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500.0,2024-02-12,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,Human Resources,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,mohammed hassan,sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,500.0,2019-03-07,john.davis@hotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,SALES,NaN,NaN,NaN,2024-09-26,peter.wilson@company.com,55859430,NaN,active,1,1,0,0
8,E009,james miller,NaN,150.0,9000.0,NaN,2020-09-13,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,-10045,FEMALE,active,0,0,0,0

# 🟡 LEVEL 4 — Text Cleaning

## Task 14 — Standardize Names

**Convert names into proper case and remove multiple spaces between words.**

**Examples:**

| **Original Value** | **Cleaned Value** |
|:---|:---|
| `"JOHN SMITH"` | `"John Smith"` |
| `"john smith"` | `"John Smith"` |
| `"John Smith"` | `"John Smith"` |
| `"mohammed  hassan"` | `"Mohammed Hassan"` |
| `"Lisa   Thomas"` | `"Lisa Thomas"` |

In [201]:
df["name"] = df["name"].str.title()
df["name"] = df["name"].str.replace(r"\s+", " ", regex=True)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,Mary Johnson,it,30.0,6000.0,NaN,2020-09-07,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT Department,35.0,7500.5,NaN,2020-03-19,mary.brown@yahoo.com,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500.0,2024-02-12,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,Human Resources,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,Mohammed Hassan,sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,500.0,2019-03-07,john.davis@hotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,SALES,NaN,NaN,NaN,2024-09-26,peter.wilson@company.com,55859430,NaN,active,1,1,0,0
8,E009,James Miller,NaN,150.0,9000.0,NaN,2020-09-13,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,-10045,FEMALE,active,0,0,0,0

# 🟡 LEVEL 4 — Text Cleaning

# Task 15 — Clean Department

**Standardize department names by fixing capitalization, extra spaces, and inconsistent department names.**

**Original Values and Expected Output:**

| **Original Value** | **Cleaned Value** |
|:---|:---|
| `IT` | `IT` |
| `it` | `IT` |
| `IT Department` | `IT` |
| `HR` | `HR` |
| `Human Resources` | `HR` |
| `Human Resource` | `HR` |
| `sales` | `Sales` |
| `Sales` | `Sales` |
| `SALES` | `Sales` |
| `Finance` | `Finance` |
| `FINANCE` | `Finance` |
| `finance` | `Finance` |
| `Operations` | `Operations` |
| `operations` | `Operations` |
| `Marketing` | `Marketing` |
| `marketing` | `Marketing` |

In [202]:
df["department"] = df["department"].str.lower()
department_clean = {
    "it" : "IT",
    "it department" : "IT",
    "hr" : "HR",
    "human resources" : "HR",
    "human resource" : "HR",
    "sales" : "Sales",
    "finance" : "Finance",
    "operations" : "Operations",
    "marketing" : "Marketing"
}

df["department"] = df["department"].map(department_clean)

df.to_excel(r"C:\Users\User\Desktop\sqldata\r.xlsx")
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,Mary Johnson,IT,30.0,6000.0,NaN,2020-09-07,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT,35.0,7500.5,NaN,2020-03-19,mary.brown@yahoo.com,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500.0,2024-02-12,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,500.0,2019-03-07,john.davis@hotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,Sales,NaN,NaN,NaN,2024-09-26,peter.wilson@company.com,55859430,NaN,active,1,1,0,0
8,E009,James Miller,NaN,150.0,9000.0,NaN,2020-09-13,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,-10045,FEMALE,active,0,0,0,0