# Pandas Data Cleaning Project

In [316]:
import pandas as pd
import numpy as np
df = pd.read_excel(r"D:\Private\555 sha\P\pandas-data-cleaning-project\data\raw_data.xlsx",keep_default_na=False)

# 🟢 LEVEL 1 — Basic Structural Cleaning
# Task 1 — Inspect the dataset

### Find : number of rows & number of columns

In [317]:
df.shape

(500, 11)

### Find : column names

In [318]:
df.columns

Index([' Employee ID ', 'NAME', 'Department', 'Age', 'Salary', 'Bonus',
       'Join Date', 'Email', 'Phone', 'Gender', 'Status'],
      dtype='str')

### Find : data types

In [319]:
df.dtypes

 Employee ID        str
NAME                str
Department          str
Age              object
Salary           object
Bonus            object
Join Date        object
Email               str
Phone            object
Gender              str
Status              str
dtype: object

### Find : memory usage

In [320]:
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0    Employee ID   500 non-null    str
 1   NAME           500 non-null    str
 2   Department     500 non-null    str
 3   Age            500 non-null    object
 4   Salary         500 non-null    object
 5   Bonus          500 non-null    object
 6   Join Date      500 non-null    object
 7   Email          500 non-null    str
 8   Phone          500 non-null    object
 9   Gender         500 non-null    str
 10  Status         500 non-null    str
dtypes: object(5), str(6)
memory usage: 284.1 KB

### Find : First 5 rows

In [321]:
df.head(5)

,Employee ID,NAME,Department,Age,Salary,Bonus,Join Date,Email,Phone,Gender,Status
0,E001,John Smith,IT,25,5000,500,unknown,noor.martin@hotmail.com,97474793157,M,N/A
1,E002,MARY JOHNSON,it,30,6000,null,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active
2,E003,,IT Department,35,7500.5,?,2020-03-19 00:00:00,mary.brown@yahoo.com,37773911,Female,A
3,E004,Sara Khan,HR,N/A,N/A,500,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive
4,E005,Robert Brown,Human Resources,42,8000,Unknown,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active

### Find : Last 5 rows

In [322]:
df.tail(5)

,Employee ID,NAME,Department,Age,Salary,Bonus,Join Date,Email,Phone,Gender,Status
495,E496,Daniel Smith,Sales,45,unknown,-50,2019-02-09 00:00:00,emma.taylor@company.com,31753140,Female,ACTIVE
496,E497,Maya Ali,IT Department,32,4800,1000,2020-02-18,ryan.taylor@hotmail.com,974-5587-2645,m,ACTIVE
497,E498,Unknown,Marketing,27,N/A,300,2020-12-15 00:00:00,amira.moore@gmail.com,974-6740-1535,female,Inactive
498,E500,Peter Khan,HR,-8,7000,not available,December 15 2019,joseph.brown@hotmail.com,-9530,M,unknown
499,E500,Hana Davis,Operations,38,6200,,16-10-2023,john..smith@gmail.com,974-7468-5012,male,INACTIVE

# Task 2 — Clean column names
### Convert: " Employee ID ", "NAME", "Department", "Join Date" Into: employee_id, name, department, join_date

In [323]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(r"\s+","_", regex=True)
df.columns

Index(['employee_id', 'name', 'department', 'age', 'salary', 'bonus',
       'join_date', 'email', 'phone', 'gender', 'status'],
      dtype='str')

# Task 3 — Remove leading/trailing whitespace
### Clean whitespace from all string columns.
### For example:, "     John Smith             ", "it                 ", "    2022-05-20             ", should become: "John Smith", "it", "2022-05-20"

In [324]:
for cl in df.select_dtypes(include="str").columns :
    df[cl] = df[cl].str.strip()
    df[cl] = df[cl].str.replace(r"\s+", " ", regex = True)    
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status
0,E001,John Smith,IT,25,5000,500,unknown,noor.martin@hotmail.com,97474793157,M,N/A
1,E002,MARY JOHNSON,it,30,6000,null,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active
2,E003,,IT Department,35,7500.5,?,2020-03-19 00:00:00,mary.brown@yahoo.com,37773911,Female,A
3,E004,Sara Khan,HR,N/A,N/A,500,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive
4,E005,Robert Brown,Human Resources,42,8000,Unknown,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active
5,E006,mohammed hassan,sales,twenty-eight,6500,-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,6028 1693,Male,Inactive
6,E007,David Wilson,Sales,29,7200,500,2019-07-03,john.davis@hotmail.com,not available,f,active
7,E008,Lisa Thomas,SALES,,,null,2024-09-26 00:00:00,peter.wilson@company.com,55859430,unknown,active
8,E009,james miller,,150,9000,,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,,
9,E010,Emma Davis,Finance,-5,-5000,500,2020-05-19,adam.anderson@yahoo.com,-10045,FEMALE,active

# Task 4 — Find completely empty strings
### Find cells containing:   ""   ,   "   "   and convert them to: NaN

In [325]:
for cl in df.columns:
    df[cl] = df[cl].replace(r"^\s*$", np.nan, regex=True)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status
0,E001,John Smith,IT,25,5000,500,unknown,noor.martin@hotmail.com,97474793157,M,N/A
1,E002,MARY JOHNSON,it,30,6000,null,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active
2,E003,NaN,IT Department,35,7500.5,?,2020-03-19 00:00:00,mary.brown@yahoo.com,37773911,Female,A
3,E004,Sara Khan,HR,N/A,N/A,500,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive
4,E005,Robert Brown,Human Resources,42,8000,Unknown,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active
5,E006,mohammed hassan,sales,twenty-eight,6500,-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,6028 1693,Male,Inactive
6,E007,David Wilson,Sales,29,7200,500,2019-07-03,john.davis@hotmail.com,not available,f,active
7,E008,Lisa Thomas,SALES,NaN,NaN,null,2024-09-26 00:00:00,peter.wilson@company.com,55859430,unknown,active
8,E009,james miller,NaN,150,9000,NaN,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN
9,E010,Emma Davis,Finance,-5,-5000,500,2020-05-19,adam.anderson@yahoo.com,-10045,FEMALE,active

# 🟢 LEVEL 2 — Missing Values
# Task 5 — Identify missing values
### Find missing values: df.isna() Then calculate missing count for every column

In [326]:
missing_values = df.isna().sum()
missing_values

employee_id     0
name            1
department      1
age             1
salary          1
bonus          37
join_date       7
email           8
phone           4
gender         27
status         26
dtype: int64

# Task 6 — Missing percentage
### Calculate: columnmissing_count , missing_percentage

In [327]:
missing_percentage = df.isna().mean() * 100.0
result = pd.DataFrame({
    "missing_count" : missing_values,
    "missing_percentage" : missing_percentage
})
result = result.reset_index(names="Column")
result

         Column  missing_count  missing_percentage
0   employee_id              0                 0.0
1          name              1                 0.2
2    department              1                 0.2
3           age              1                 0.2
4        salary              1                 0.2
5         bonus             37                 7.4
6     join_date              7                 1.4
7         email              8                 1.6
8         phone              4                 0.8
9        gender             27                 5.4
10       status             26                 5.2

# Task 7 — Replace fake missing values
### Convert these into actual NaN:  "N/A", "NULL" ,"unknown" , "Unknown" , ""

In [328]:
fake_missing = ["N/A","NULL","unknown","Unknown","", "null"]
for cl in df.columns:
    df[cl] = df[cl].replace(fake_missing,np.nan)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status
0,E001,John Smith,IT,25,5000,500,NaN,noor.martin@hotmail.com,97474793157,M,NaN
1,E002,MARY JOHNSON,it,30,6000,NaN,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active
2,E003,NaN,IT Department,35,7500.5,?,2020-03-19 00:00:00,mary.brown@yahoo.com,37773911,Female,A
3,E004,Sara Khan,HR,NaN,NaN,500,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive
4,E005,Robert Brown,Human Resources,42,8000,NaN,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active
5,E006,mohammed hassan,sales,twenty-eight,6500,-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,6028 1693,Male,Inactive
6,E007,David Wilson,Sales,29,7200,500,2019-07-03,john.davis@hotmail.com,not available,f,active
7,E008,Lisa Thomas,SALES,NaN,NaN,NaN,2024-09-26 00:00:00,peter.wilson@company.com,55859430,NaN,active
8,E009,james miller,NaN,150,9000,NaN,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN
9,E010,Emma Davis,Finance,-5,-5000,500,2020-05-19,adam.anderson@yahoo.com,-10045,FEMALE,active