# Python Pandas Data Cleaning

In [406]:
import pandas as pd
import numpy as np
df = pd.read_excel(r"D:\Private\555 sha\P\pandas-data-cleaning-project\data\raw_data.xlsx", dtype="str",keep_default_na=False)

# 🟢 LEVEL 1 — Basic Structural Cleaning

## Task 1 — Inspect the Dataset

**Find:**
- **Number of rows**
- **Number of columns**
- **Column names**
- **Data types**
- **Memory usage**
- **First 5 rows**
- **Last 5 rows**

In [407]:
df.shape

(500, 11)

In [408]:
df.columns

Index([' Employee ID ', 'NAME', 'Department', 'Age', 'Salary', 'Bonus',
       'Join Date', 'Email', 'Phone', 'Gender', 'Status'],
      dtype='str')

In [409]:
df.dtypes

 Employee ID     str
NAME             str
Department       str
Age              str
Salary           str
Bonus            str
Join Date        str
Email            str
Phone            str
Gender           str
Status           str
dtype: object

In [410]:
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0    Employee ID   500 non-null    str
 1   NAME           500 non-null    str
 2   Department     500 non-null    str
 3   Age            500 non-null    str
 4   Salary         500 non-null    str
 5   Bonus          500 non-null    str
 6   Join Date      500 non-null    str
 7   Email          500 non-null    str
 8   Phone          500 non-null    str
 9   Gender         500 non-null    str
 10  Status         500 non-null    str
dtypes: str(11)
memory usage: 307.4 KB

In [411]:
df.head(5)

,Employee ID,NAME,Department,Age,Salary,Bonus,Join Date,Email,Phone,Gender,Status
0,E001,John Smith,IT,25,"$5,000",$500,unknown,noor.martin@hotmail.com,97474793157,M,N/A
1,E002,MARY JOHNSON,it,30,16000,null,2040-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active
2,E003,,IT Department,35,"7,500",?,2020-03-19 00:00:00,mary.brown@yahoo,37773911,Female,A
3,E004,Sara Khan,HR,N/A,N/A,500,2020/13/01,daniel.johnson@yahoo.com,37855874,Female,Inactive
4,E005,Robert Brown,Human Resources,42,"8,000",Unknown,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active

In [412]:
df.tail(5)

,Employee ID,NAME,Department,Age,Salary,Bonus,Join Date,Email,Phone,Gender,Status
495,E496,Daniel Smith,Sales,45,unknown,-50,2019-02-09 00:00:00,emma.taylor@company.com,31753140,Female,ACTIVE
496,E497,Maya Ali,IT Department,32,"4,800","1,000",2020-02-18,ryan.taylor@hotmail.com,974-5587-2645,m,ACTIVE
497,E498,Unknown,Marketing,27,N/A,300,2020-12-15 00:00:00,amira.moore@gmail.com,974-6740-1535,female,Inactive
498,E500,Hana Davis,Operations,38,"6,200",0,16-10-2023,john..smith@gmail.com,974-7468-5012,male,INACTIVE
499,E500,Hana Davis,Operations,38,"6,200",0,16-10-2023,john..smith@gmail.com,974-7468-5012,male,INACTIVE

# 🟢 LEVEL 1 — Basic Structural Cleaning

## Task 2 — Clean Column Names

**Convert column names into lowercase, remove extra spaces, and replace spaces between words with underscores.**

**Example:**
- `" Employee ID "` → `employee_id`
- `"NAME"` → `name`
- `"Department"` → `department`
- `"Join Date"` → `join_date`

In [413]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(r"\s+","_", regex=True)
df.columns

Index(['employee_id', 'name', 'department', 'age', 'salary', 'bonus',
       'join_date', 'email', 'phone', 'gender', 'status'],
      dtype='str')

# 🟢 LEVEL 1 — Basic Structural Cleaning

## Task 3 — Remove Leading and Trailing Whitespace

**Clean leading and trailing whitespace from all string columns.**

**Examples:**
- `"     John Smith     "` → `"John Smith"`
- `"it          "` → `"it"`
- `"    2022-05-20     "` → `"2022-05-20"`

In [414]:
for cl in df.select_dtypes(include="str").columns :
    df[cl] = df[cl].str.strip()
    df[cl] = df[cl].str.replace(r"\s+", " ", regex = True)    
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status
0,E001,John Smith,IT,25,"$5,000",$500,unknown,noor.martin@hotmail.com,97474793157,M,N/A
1,E002,MARY JOHNSON,it,30,16000,null,2040-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active
2,E003,,IT Department,35,"7,500",?,2020-03-19 00:00:00,mary.brown@yahoo,37773911,Female,A
3,E004,Sara Khan,HR,N/A,N/A,500,2020/13/01,daniel.johnson@yahoo.com,37855874,Female,Inactive
4,E005,Robert Brown,Human Resources,42,"8,000",Unknown,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active
5,E006,mohammed hassan,sales,twenty-eight,"6,500",-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive
6,E007,David Wilson,Sales,29,"7,200","1,200",invalid,john.davishotmail.com,not available,f,active
7,E008,Lisa Thomas,SALES,,0,null,2039-09-26 00:00:00,peter.wilson@company.com,55859430,unknown,active
8,E009,james miller,,150,"$9,000",0,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,,
9,E010,Emma Davis,Finance,-5,"-5,000",500,2020-05-19,adam.anderson@yahoo.com,6028 1693,FEMALE,active

# 🟢 LEVEL 1 — Basic Structural Cleaning

## Task 4 — Find Completely Empty Strings

- **Find cells containing empty strings (`""`) or strings with only whitespace (`"   "`).**
- **Replace them with `NaN`.**

In [415]:
for cl in df.columns:
    df[cl] = df[cl].replace(r"^\s*$", np.nan, regex=True)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status
0,E001,John Smith,IT,25,"$5,000",$500,unknown,noor.martin@hotmail.com,97474793157,M,N/A
1,E002,MARY JOHNSON,it,30,16000,null,2040-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active
2,E003,NaN,IT Department,35,"7,500",?,2020-03-19 00:00:00,mary.brown@yahoo,37773911,Female,A
3,E004,Sara Khan,HR,N/A,N/A,500,2020/13/01,daniel.johnson@yahoo.com,37855874,Female,Inactive
4,E005,Robert Brown,Human Resources,42,"8,000",Unknown,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active
5,E006,mohammed hassan,sales,twenty-eight,"6,500",-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive
6,E007,David Wilson,Sales,29,"7,200","1,200",invalid,john.davishotmail.com,not available,f,active
7,E008,Lisa Thomas,SALES,NaN,0,null,2039-09-26 00:00:00,peter.wilson@company.com,55859430,unknown,active
8,E009,james miller,NaN,150,"$9,000",0,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN
9,E010,Emma Davis,Finance,-5,"-5,000",500,2020-05-19,adam.anderson@yahoo.com,6028 1693,FEMALE,active

# 🟢 LEVEL 2 — Missing Values

## Task 5 — Identify Missing Values

- **Identify missing values using `df.isna()`.**
- **Calculate the missing value count for every column.**

In [416]:
missing_values = df.isna().sum()
missing_values

employee_id     0
name            1
department      1
age             1
salary          0
bonus          11
join_date       7
email           8
phone           4
gender         27
status         26
dtype: int64

# 🟢 LEVEL 2 — Missing Values

## Task 6 — Calculate Missing Percentage

- **Calculate the missing value count for every column.**
- **Calculate the missing percentage for every column.**

In [417]:
missing_percentage = df.isna().mean() * 100.0
result = pd.DataFrame({
    "missing_count" : missing_values,
    "missing_percentage" : missing_percentage
})
result = result.reset_index(names="Column")
result

         Column  missing_count  missing_percentage
0   employee_id              0                 0.0
1          name              1                 0.2
2    department              1                 0.2
3           age              1                 0.2
4        salary              0                 0.0
5         bonus             11                 2.2
6     join_date              7                 1.4
7         email              8                 1.6
8         phone              4                 0.8
9        gender             27                 5.4
10       status             26                 5.2

# 🟢 LEVEL 2 — Missing Values

## Task 7 — Replace Fake Missing Values

**Convert the following fake missing values into actual `NaN`:**

- **`"N/A"`**
- **`"NULL"`**
- **`"unknown"`**
- **`"Unknown"`**
- **`""`** (empty string)

In [418]:
fake_missing = ["N/A","NULL","unknown","Unknown","", "null"]
for cl in df.columns:
    df[cl] = df[cl].replace(fake_missing,np.nan)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status
0,E001,John Smith,IT,25,"$5,000",$500,NaN,noor.martin@hotmail.com,97474793157,M,NaN
1,E002,MARY JOHNSON,it,30,16000,NaN,2040-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active
2,E003,NaN,IT Department,35,"7,500",?,2020-03-19 00:00:00,mary.brown@yahoo,37773911,Female,A
3,E004,Sara Khan,HR,NaN,NaN,500,2020/13/01,daniel.johnson@yahoo.com,37855874,Female,Inactive
4,E005,Robert Brown,Human Resources,42,"8,000",NaN,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active
5,E006,mohammed hassan,sales,twenty-eight,"6,500",-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive
6,E007,David Wilson,Sales,29,"7,200","1,200",invalid,john.davishotmail.com,not available,f,active
7,E008,Lisa Thomas,SALES,NaN,0,NaN,2039-09-26 00:00:00,peter.wilson@company.com,55859430,NaN,active
8,E009,james miller,NaN,150,"$9,000",0,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN
9,E010,Emma Davis,Finance,-5,"-5,000",500,2020-05-19,adam.anderson@yahoo.com,6028 1693,FEMALE,active

## 🟢 LEVEL 2 — Missing Values

# Task 8 — Decide How to Handle Missing Values

**Missing-value treatment will be performed after completing the data-cleaning and data-type conversion tasks to avoid affecting subsequent analysis.**

**The appropriate strategy will be selected based on each column's meaning and the amount of missing data.**

# 🟢 LEVEL 2 — Missing Values

## Task 9 — Create Missing Indicators

**Create the following columns:**
- **`age_missing`**
- **`salary_missing`**
- **`email_missing`**
- **`phone_missing`**

**Example:**
- **`age = NaN` → `age_missing = 1`**
- **`age = 25` → `age_missing = 0`**

In [419]:
missing_columns = ['age','salary','email','phone']
for cl in missing_columns:
    df[cl+"_missing"] = df[cl].isna().astype("int")
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25,"$5,000",$500,NaN,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,MARY JOHNSON,it,30,16000,NaN,2040-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT Department,35,"7,500",?,2020-03-19 00:00:00,mary.brown@yahoo,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500,2020/13/01,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,Human Resources,42,"8,000",NaN,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,mohammed hassan,sales,twenty-eight,"6,500",-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29,"7,200","1,200",invalid,john.davishotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,SALES,NaN,0,NaN,2039-09-26 00:00:00,peter.wilson@company.com,55859430,NaN,active,1,0,0,0
8,E009,james miller,NaN,150,"$9,000",0,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5,"-5,000",500,2020-05-19,adam.anderson@yahoo.com,6028 1693,FEMALE,active,0,0,0,0

# 🟡 LEVEL 3 — Data Types

## Task 10 — Convert Age
**Currently:**
- **`"25"`**
- **`" 30 "`**
- **`"35"`**
- **`"twenty-eight"`**
- **`"N/A"`**
**Objective: Convert `age` into numeric values.**
**Expected result: Invalid values should become `NaN`**

In [420]:
df["age"] = pd.to_numeric(df["age"], errors="coerce")
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,"$5,000",$500,NaN,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,MARY JOHNSON,it,30.0,16000,NaN,2040-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT Department,35.0,"7,500",?,2020-03-19 00:00:00,mary.brown@yahoo,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500,2020/13/01,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,Human Resources,42.0,"8,000",NaN,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,mohammed hassan,sales,NaN,"6,500",-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,"7,200","1,200",invalid,john.davishotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,SALES,NaN,0,NaN,2039-09-26 00:00:00,peter.wilson@company.com,55859430,NaN,active,1,0,0,0
8,E009,james miller,NaN,150.0,"$9,000",0,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,"-5,000",500,2020-05-19,adam.anderson@yahoo.com,6028 1693,FEMALE,active,0,0,0,0

# 🟡 LEVEL 3 — Data Types

## Task 11 — Convert Salary

**Currently:**
- **`"$5,000"`**
- **`"6000"`**
- **`"7,500.50"`**
- **`"8,000"`**

**Objective: Remove currency symbols and commas, then convert `salary` into numeric values.**

**Expected result:**
- **`5000`**
- **`6000`**
- **`7500.50`**
- **`8000`**

In [421]:
df["salary"] = df["salary"].str.replace('$',"", regex=False)
df["salary"] = df["salary"].str.replace(',',"", regex=False)
df["salary"] = pd.to_numeric(df["salary"], errors="coerce")
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,$500,NaN,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,MARY JOHNSON,it,30.0,16000.0,NaN,2040-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT Department,35.0,7500.0,?,2020-03-19 00:00:00,mary.brown@yahoo,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500,2020/13/01,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,Human Resources,42.0,8000.0,NaN,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,mohammed hassan,sales,NaN,6500.0,-50,2020-10-23 00:00:00,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,"1,200",invalid,john.davishotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,SALES,NaN,0.0,NaN,2039-09-26 00:00:00,peter.wilson@company.com,55859430,NaN,active,1,0,0,0
8,E009,james miller,NaN,150.0,9000.0,0,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500,2020-05-19,adam.anderson@yahoo.com,6028 1693,FEMALE,active,0,0,0,0

# 🟡 LEVEL 3 — Data Types

## Task 12 — Convert Bonus to Numeric

**Clean the `bonus` column and convert it to a numeric data type.**

**Example values:**
- **`"$750"`**
- **`"1000"`**
- **`"-200"`**
- **`"unknown"`**

**Expected result:**
- **`"$750"` → `750`**
- **`"1000"` → `1000`**
- **`"-200"` → `-200`**
- **`"unknown"` → `NaN`**

In [422]:
df["bonus"] = df["bonus"].str.replace("$" ,"", regex=False)
df["bonus"] = df["bonus"].str.replace("," ,"" ,regex=False)
df["bonus"] = pd.to_numeric(df["bonus"], errors="coerce")
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,500.0,NaN,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,MARY JOHNSON,it,30.0,16000.0,NaN,2040-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT Department,35.0,7500.0,NaN,2020-03-19 00:00:00,mary.brown@yahoo,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500.0,2020/13/01,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,Human Resources,42.0,8000.0,NaN,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,mohammed hassan,sales,NaN,6500.0,-50.0,2020-10-23 00:00:00,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,1200.0,invalid,john.davishotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,SALES,NaN,0.0,NaN,2039-09-26 00:00:00,peter.wilson@company.com,55859430,NaN,active,1,0,0,0
8,E009,james miller,NaN,150.0,9000.0,0.0,September 13 2020,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,6028 1693,FEMALE,active,0,0,0,0

# 🟡 LEVEL 3 — Data Types

## Task 13 — Convert Join Date

**Convert all valid dates into Pandas datetime.**

**Invalid values such as:**
```
invalid
N/A
```

**should become:**
```
NaT
```

In [423]:
df["join_date"] = pd.to_datetime(df["join_date"], errors="coerce", format="mixed", dayfirst=True)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,MARY JOHNSON,it,30.0,16000.0,NaN,2040-09-07,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT Department,35.0,7500.0,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500.0,2020-01-13,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,Human Resources,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,mohammed hassan,sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,1200.0,NaT,john.davishotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,SALES,NaN,0.0,NaN,2039-09-26,peter.wilson@company.com,55859430,NaN,active,1,0,0,0
8,E009,james miller,NaN,150.0,9000.0,0.0,2020-09-13,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,6028 1693,FEMALE,active,0,0,0,0

# 🟡 LEVEL 4 — Text Cleaning

## Task 14 — Standardize Names

**Convert names into proper case and remove multiple spaces between words.**

**Examples:**

**Expected result:**

- **`"JOHN SMITH"` → `"John Smith"`**
- **`"john smith"` → `"John Smith"`**
- **`"John Smith"` → `"John Smith"`**
- **`"mohammed  hassan"` → `"Mohammed Hassan"`**
- **`"Lisa   Thomas"` → `"Lisa Thomas"`**

In [424]:
df["name"] = df["name"].str.title()
df["name"] = df["name"].str.replace(r"\s+", " ", regex=True)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,Mary Johnson,it,30.0,16000.0,NaN,2040-09-07,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT Department,35.0,7500.0,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500.0,2020-01-13,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,Human Resources,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,Mohammed Hassan,sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,1200.0,NaT,john.davishotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,SALES,NaN,0.0,NaN,2039-09-26,peter.wilson@company.com,55859430,NaN,active,1,0,0,0
8,E009,James Miller,NaN,150.0,9000.0,0.0,2020-09-13,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,6028 1693,FEMALE,active,0,0,0,0

# 🟡 LEVEL 4 — Text Cleaning

# Task 15 — Clean Department

**Standardize department names by fixing capitalization, extra spaces, and inconsistent department names.**

**Original Values and Expected Output:**

**Expected result:**

- **`"IT"` → `"IT"`**
- **`"it"` → `"IT"`**
- **`"IT Department"` → `"IT"`**
- **`"HR"` → `"HR"`**
- **`"Human Resources"` → `"HR"`**
- **`"Human Resource"` → `"HR"`**
- **`"sales"` → `"Sales"`**
- **`"Sales"` → `"Sales"`**
- **`"SALES"` → `"Sales"`**
- **`"Finance"` → `"Finance"`**
- **`"FINANCE"` → `"Finance"`**
- **`"finance"` → `"Finance"`**
- **`"Operations"` → `"Operations"`**
- **`"operations"` → `"Operations"`**
- **`"Marketing"` → `"Marketing"`**
- **`"marketing"` → `"Marketing"`**

In [425]:
df["department"] = df["department"].str.lower()
department_clean = {
    "it" : "IT",
    "it department" : "IT",
    "hr" : "HR",
    "human resources" : "HR",
    "human resource" : "HR",
    "sales" : "Sales",
    "finance" : "Finance",
    "operations" : "Operations",
    "marketing" : "Marketing"
}

df["department"] = df["department"].map(department_clean)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,M,NaN,0,0,0,0
1,E002,Mary Johnson,IT,30.0,16000.0,NaN,2040-09-07,joseph.yusuf@gmail.com,+974 7824 2882,f,Active,0,0,0,0
2,E003,NaN,IT,35.0,7500.0,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500.0,2020-01-13,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,1200.0,NaT,john.davishotmail.com,not available,f,active,0,0,0,0
7,E008,Lisa Thomas,Sales,NaN,0.0,NaN,2039-09-26,peter.wilson@company.com,55859430,NaN,active,1,0,0,0
8,E009,James Miller,NaN,150.0,9000.0,0.0,2020-09-13,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,6028 1693,FEMALE,active,0,0,0,0

# 🟡 LEVEL 4 — Text Cleaning

# Task 16 — Clean Gender

**Standardize gender values by converting inconsistent capitalization and abbreviations into consistent categories.**

**Expected result:**

- **`"Male"` → `"Male"`**
- **`"MALE"` → `"Male"`**
- **`"M"` → `"Male"`**
- **`"m"` → `"Male"`**
- **`"Female"` → `"Female"`**
- **`"F"` → `"Female"`**
- **`"female"` → `"Female"`**
- **`"other"` → `"Other"`**

In [426]:
gnder_clean ={
    "male" : "Male",
    "m" : "Male",
    "female" : "Female",
    "f": "Female",
    "other" : "Other"
}

df["gender"] = df["gender"].str.lower()
df["gender"] = df["gender"].map(gnder_clean)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,NaN,0,0,0,0
1,E002,Mary Johnson,IT,30.0,16000.0,NaN,2040-09-07,joseph.yusuf@gmail.com,+974 7824 2882,Female,Active,0,0,0,0
2,E003,NaN,IT,35.0,7500.0,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,A,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500.0,2020-01-13,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,+974 5995 1676,Male,active,0,0,0,0
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,1200.0,NaT,john.davishotmail.com,not available,Female,active,0,0,0,0
7,E008,Lisa Thomas,Sales,NaN,0.0,NaN,2039-09-26,peter.wilson@company.com,55859430,NaN,active,1,0,0,0
8,E009,James Miller,NaN,150.0,9000.0,0.0,2020-09-13,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,6028 1693,Female,active,0,0,0,0

# 🟡 LEVEL 4 — Text Cleaning

## Task 17 — Clean Status

**Currently:**
- **`Active`**
- **`active`**
- **`ACTIVE`**
- **`A`**
- **`Inactive`**
- **`inactive`**
- **`INACTIVE`**
- **`I`**

**Objective:   Standardize status values into consistent categories.**

**Expected result:**
- **`Active`, `active`, `ACTIVE`, `A` → `Active`**
- **`Inactive`, `inactive`, `INACTIVE`, `I` → `Inactive`**

In [427]:
status_clean = {
    'active': "Active",
    'a' : "Active",
    'inactive' : "Inactive",
    'i' : "Inactive",
    'in active' : "Inactive"
}

df["status"] = df.status.str.lower()
df["status"] = df["status"].map(status_clean)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,NaN,0,0,0,0
1,E002,Mary Johnson,IT,30.0,16000.0,NaN,2040-09-07,joseph.yusuf@gmail.com,+974 7824 2882,Female,Active,0,0,0,0
2,E003,NaN,IT,35.0,7500.0,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,Active,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500.0,2020-01-13,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,+974 5995 1676,Male,Active,0,0,0,0
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,1200.0,NaT,john.davishotmail.com,not available,Female,Active,0,0,0,0
7,E008,Lisa Thomas,Sales,NaN,0.0,NaN,2039-09-26,peter.wilson@company.com,55859430,NaN,Active,1,0,0,0
8,E009,James Miller,NaN,150.0,9000.0,0.0,2020-09-13,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,6028 1693,Female,Active,0,0,0,0

# 🟡 LEVEL 5 — Email Cleaning

# Task 18 — Clean Email Whitespace

**Currently:**
- **`" mary.johnson@gmail.com "`**

**Objective:** **Remove leading and trailing whitespace from email addresses.**

**Expected result:**
- **`"mary.johnson@gmail.com"`**

In [428]:
df["email"] = df["email"].str.strip()
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,NaN,0,0,0,0
1,E002,Mary Johnson,IT,30.0,16000.0,NaN,2040-09-07,joseph.yusuf@gmail.com,+974 7824 2882,Female,Active,0,0,0,0
2,E003,NaN,IT,35.0,7500.0,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,Active,0,0,0,0
3,E004,Sara Khan,HR,NaN,NaN,500.0,2020-01-13,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,+974 5995 1676,Male,Active,0,0,0,0
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0
6,E007,David Wilson,Sales,29.0,7200.0,1200.0,NaT,john.davishotmail.com,not available,Female,Active,0,0,0,0
7,E008,Lisa Thomas,Sales,NaN,0.0,NaN,2039-09-26,peter.wilson@company.com,55859430,NaN,Active,1,0,0,0
8,E009,James Miller,NaN,150.0,9000.0,0.0,2020-09-13,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,6028 1693,Female,Active,0,0,0,0

# 🟡 LEVEL 5 — Email Cleaning

# Task 19 — Validate email addresses

**A valid email should roughly follow:**
```
something@domain.extension
```

**Identify invalid emails:**
```
sarakhan@gmail
james.miller@gmail
unknown
```
**Output column:   `email_valid`**

**Do not delete them immediately**

In [429]:
df["email_valid"] = df["email"].str.match(r"^[a-zA-Z0-9-.%+_]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$")
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing,email_valid
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,NaN,0,0,0,0,True
1,E002,Mary Johnson,IT,30.0,16000.0,NaN,2040-09-07,joseph.yusuf@gmail.com,+974 7824 2882,Female,Active,0,0,0,0,True
2,E003,NaN,IT,35.0,7500.0,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,Active,0,0,0,0,False
3,E004,Sara Khan,HR,NaN,NaN,500.0,2020-01-13,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0,True
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,+974 5995 1676,Male,Active,0,0,0,0,True
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0,True
6,E007,David Wilson,Sales,29.0,7200.0,1200.0,NaT,john.davishotmail.com,not available,Female,Active,0,0,0,0,False
7,E008,Lisa Thomas,Sales,NaN,0.0,NaN,2039-09-26,peter.wilson@company.com,55859430,NaN,Active,1,0,0,0,True
8,E009,James Miller,NaN,150.0,9000.0,0.0,2020-09-13,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0,True
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,6028 1693,Female,Active,0,0,0,0,True

# 🟡 LEVEL 5 — Email Cleaning

## Task 20 — Extract Email Domain

**Objective: Extract the domain from each email address and store it in a new column named   `email_domain`**.

**Currently:**
- **`john.smith@gmail.com`**

**Expected result:**
- **`gmail.com`**
- **`yahoo.com`**
- **`company.com`**

**Output column:   `email_domain`**

In [430]:
df["email_domain"] = df["email"].str.extract(r"@(.+)")
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing,email_valid,email_domain
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,NaN,0,0,0,0,True,hotmail.com
1,E002,Mary Johnson,IT,30.0,16000.0,NaN,2040-09-07,joseph.yusuf@gmail.com,+974 7824 2882,Female,Active,0,0,0,0,True,gmail.com
2,E003,NaN,IT,35.0,7500.0,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,Active,0,0,0,0,False,yahoo
3,E004,Sara Khan,HR,NaN,NaN,500.0,2020-01-13,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0,True,yahoo.com
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,+974 5995 1676,Male,Active,0,0,0,0,True,hotmail.com
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,+6028 1693,Male,Inactive,0,0,0,0,True,yahoo.com
6,E007,David Wilson,Sales,29.0,7200.0,1200.0,NaT,john.davishotmail.com,not available,Female,Active,0,0,0,0,False,NaN
7,E008,Lisa Thomas,Sales,NaN,0.0,NaN,2039-09-26,peter.wilson@company.com,55859430,NaN,Active,1,0,0,0,True,company.com
8,E009,James Miller,NaN,150.0,9000.0,0.0,2020-09-13,zainab.martin@yahoo.com,+974 3313 8535,NaN,NaN,0,0,0,0,True,yahoo.com
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,6028 1693,Female,Active,0,0,0,0,True,yahoo.com

# 🟠 LEVEL 6 — Phone Cleaning

# Task 21 — Remove Phone Formatting

**Objective:  Remove spaces, hyphens, and other non-digit characters from phone numbers.**

**Currently:**
- **`+974 5555 1111`**
- **`974-5555-2222`**
- **`974 5555 5555`**
- **`+974-5555-8888`**

**Expected result:**
- **`97455551111`**
- **`97455552222`**
- **`97455555555`**
- **`97455558888`**

In [431]:
df["phone"] = df["phone"].str.replace(r"\D","", regex=True)
df["phone"] = df["phone"].replace("", np.nan)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing,email_valid,email_domain
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,NaN,0,0,0,0,True,hotmail.com
1,E002,Mary Johnson,IT,30.0,16000.0,NaN,2040-09-07,joseph.yusuf@gmail.com,97478242882,Female,Active,0,0,0,0,True,gmail.com
2,E003,NaN,IT,35.0,7500.0,NaN,2020-03-19,mary.brown@yahoo,37773911,Female,Active,0,0,0,0,False,yahoo
3,E004,Sara Khan,HR,NaN,NaN,500.0,2020-01-13,daniel.johnson@yahoo.com,37855874,Female,Inactive,1,1,0,0,True,yahoo.com
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,97459951676,Male,Active,0,0,0,0,True,hotmail.com
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,60281693,Male,Inactive,0,0,0,0,True,yahoo.com
6,E007,David Wilson,Sales,29.0,7200.0,1200.0,NaT,john.davishotmail.com,NaN,Female,Active,0,0,0,0,False,NaN
7,E008,Lisa Thomas,Sales,NaN,0.0,NaN,2039-09-26,peter.wilson@company.com,55859430,NaN,Active,1,0,0,0,True,company.com
8,E009,James Miller,NaN,150.0,9000.0,0.0,2020-09-13,zainab.martin@yahoo.com,97433138535,NaN,NaN,0,0,0,0,True,yahoo.com
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,60281693,Female,Active,0,0,0,0,True,yahoo.com

# 🟠 LEVEL 6 — Phone Cleaning

## Task 22 — Standardize Qatar Phone Numbers

**Objective:  Standardize Qatar phone numbers into the format `974XXXXXXXX`, where appropriate.**

**Expected Format:**
- **`974` followed by exactly 8 digits.**

**Tasks:**
- **Add the country code `974` to phone numbers containing exactly 8 digits.**
- **Identify phone numbers that match the expected pattern.**
- **Identify phone numbers that do not match the expected pattern.**
- **Create a new column named `phone_valid`.**

**Expected Results:**

| Original Phone | Standardized Phone | phone_valid |
|---|---|---|
| `55551111` | `97455551111` | `True` |
| `97455551111` | `97455551111` | `True` |
| `9745555222` | `9745555222` | `False` |
| `12345678901` | `12345678901` | `False` |

**Important:**
- **Only add `974` to numbers containing exactly 8 digits.**
- **Do not modify numbers that already contain the country code.**
- **Do not delete invalid phone numbers immediately; retain them for further review.**

In [432]:
df.loc[df["phone"].str.len() == 8, "phone"] = '974' + df.loc[df["phone"].str.len() == 8, "phone"]
df["phone_valid"] = df["phone"].str.fullmatch(r"974\d{8}$")
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing,email_valid,email_domain,phone_valid
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,NaN,0,0,0,0,True,hotmail.com,True
1,E002,Mary Johnson,IT,30.0,16000.0,NaN,2040-09-07,joseph.yusuf@gmail.com,97478242882,Female,Active,0,0,0,0,True,gmail.com,True
2,E003,NaN,IT,35.0,7500.0,NaN,2020-03-19,mary.brown@yahoo,97437773911,Female,Active,0,0,0,0,False,yahoo,True
3,E004,Sara Khan,HR,NaN,NaN,500.0,2020-01-13,daniel.johnson@yahoo.com,97437855874,Female,Inactive,1,1,0,0,True,yahoo.com,True
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,97459951676,Male,Active,0,0,0,0,True,hotmail.com,True
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,97460281693,Male,Inactive,0,0,0,0,True,yahoo.com,True
6,E007,David Wilson,Sales,29.0,7200.0,1200.0,NaT,john.davishotmail.com,NaN,Female,Active,0,0,0,0,False,NaN,False
7,E008,Lisa Thomas,Sales,NaN,0.0,NaN,2039-09-26,peter.wilson@company.com,97455859430,NaN,Active,1,0,0,0,True,company.com,True
8,E009,James Miller,NaN,150.0,9000.0,0.0,2020-09-13,zainab.martin@yahoo.com,97433138535,NaN,NaN,0,0,0,0,True,yahoo.com,True
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,97460281693,Female,Active,0,0,0,0,True,yahoo.com,True

# 🟠 LEVEL 7 — Numeric Validation

# Task 23 — Find Invalid Ages

**Objective: Identify employee ages that fall outside the valid range.**

**Valid age range: 18–65 (inclusive)**

**Examples of invalid ages:**
- **`150`**
- **`-5`**

**Task: 
Create a new column named `age_valid` to indicate whether each employee's age is within the valid range.**

**Expected result:**
- **`150` → `False`**
- **`-5` → `False`**
- **`25` → `True`**

**Important: Identify invalid ages without deleting them immediately.**

In [433]:
df["age_valid"] = df["age"].between(18,65, inclusive="both")
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing,email_valid,email_domain,phone_valid,age_valid
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,NaN,0,0,0,0,True,hotmail.com,True,True
1,E002,Mary Johnson,IT,30.0,16000.0,NaN,2040-09-07,joseph.yusuf@gmail.com,97478242882,Female,Active,0,0,0,0,True,gmail.com,True,True
2,E003,NaN,IT,35.0,7500.0,NaN,2020-03-19,mary.brown@yahoo,97437773911,Female,Active,0,0,0,0,False,yahoo,True,True
3,E004,Sara Khan,HR,NaN,NaN,500.0,2020-01-13,daniel.johnson@yahoo.com,97437855874,Female,Inactive,1,1,0,0,True,yahoo.com,True,False
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,97459951676,Male,Active,0,0,0,0,True,hotmail.com,True,True
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,97460281693,Male,Inactive,0,0,0,0,True,yahoo.com,True,False
6,E007,David Wilson,Sales,29.0,7200.0,1200.0,NaT,john.davishotmail.com,NaN,Female,Active,0,0,0,0,False,NaN,False,True
7,E008,Lisa Thomas,Sales,NaN,0.0,NaN,2039-09-26,peter.wilson@company.com,97455859430,NaN,Active,1,0,0,0,True,company.com,True,False
8,E009,James Miller,NaN,150.0,9000.0,0.0,2020-09-13,zainab.martin@yahoo.com,97433138535,NaN,NaN,0,0,0,0,True,yahoo.com,True,False
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,97460281693,Female,Active,0,0,0,0,True,yahoo.com,True,False

# 🟠 LEVEL 7 — Numeric Validation

# Task 24 — Find Invalid Salaries

**Objective:  Identify salaries that do not meet the valid salary condition.**

**Valid salary condition:  Salary must be greater than `0`.**

**Example of an invalid salary:**
- **`-5000`**

**Task:
Create a new column named `salary_valid` to indicate whether each salary is valid.**

**Expected result:**
- **`-5000` → `False`**
- **`5000` → `True`**
- **`0` → `False`**

**Important:  Identify invalid salaries without deleting or modifying the original values.**

In [434]:
df["salary_valid"] = df["salary"] > 0
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,status,age_missing,salary_missing,email_missing,phone_missing,email_valid,email_domain,phone_valid,age_valid,salary_valid
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,NaN,0,0,0,0,True,hotmail.com,True,True,True
1,E002,Mary Johnson,IT,30.0,16000.0,NaN,2040-09-07,joseph.yusuf@gmail.com,97478242882,Female,Active,0,0,0,0,True,gmail.com,True,True,True
2,E003,NaN,IT,35.0,7500.0,NaN,2020-03-19,mary.brown@yahoo,97437773911,Female,Active,0,0,0,0,False,yahoo,True,True,True
3,E004,Sara Khan,HR,NaN,NaN,500.0,2020-01-13,daniel.johnson@yahoo.com,97437855874,Female,Inactive,1,1,0,0,True,yahoo.com,True,False,False
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,97459951676,Male,Active,0,0,0,0,True,hotmail.com,True,True,True
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,97460281693,Male,Inactive,0,0,0,0,True,yahoo.com,True,False,True
6,E007,David Wilson,Sales,29.0,7200.0,1200.0,NaT,john.davishotmail.com,NaN,Female,Active,0,0,0,0,False,NaN,False,True,True
7,E008,Lisa Thomas,Sales,NaN,0.0,NaN,2039-09-26,peter.wilson@company.com,97455859430,NaN,Active,1,0,0,0,True,company.com,True,False,False
8,E009,James Miller,NaN,150.0,9000.0,0.0,2020-09-13,zainab.martin@yahoo.com,97433138535,NaN,NaN,0,0,0,0,True,yahoo.com,True,False,True
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,97460281693,Female,Active,0,0,0,0,True,yahoo.com,True,False,False

# 🟠 LEVEL 7 — Numeric Validation

# Task 25 — Find Invalid Bonuses

**Objective:   Identify bonus values that do not meet the valid bonus condition.**

**Valid bonus condition:    Bonus must be greater than or equal to `0`.**

**Example of an invalid bonus:**
- **`-200`**

**Task:
Create a new column named `bonus_valid` to indicate whether each bonus is valid.**

**Expected result:**
- **`-200` → `False`**
- **`500` → `True`**
- **`0` → `True`**

**Important:   Identify invalid bonuses without deleting or modifying the original values.**

In [435]:
df["bonus_valid"] = df["bonus"] >=0
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,...,age_missing,salary_missing,email_missing,phone_missing,email_valid,email_domain,phone_valid,age_valid,salary_valid,bonus_valid
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,...,0,0,0,0,True,hotmail.com,True,True,True,True
1,E002,Mary Johnson,IT,30.0,16000.0,NaN,2040-09-07,joseph.yusuf@gmail.com,97478242882,Female,...,0,0,0,0,True,gmail.com,True,True,True,False
2,E003,NaN,IT,35.0,7500.0,NaN,2020-03-19,mary.brown@yahoo,97437773911,Female,...,0,0,0,0,False,yahoo,True,True,True,False
3,E004,Sara Khan,HR,NaN,NaN,500.0,2020-01-13,daniel.johnson@yahoo.com,97437855874,Female,...,1,1,0,0,True,yahoo.com,True,False,False,True
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,97459951676,Male,...,0,0,0,0,True,hotmail.com,True,True,True,False
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,97460281693,Male,...,0,0,0,0,True,yahoo.com,True,False,True,False
6,E007,David Wilson,Sales,29.0,7200.0,1200.0,NaT,john.davishotmail.com,NaN,Female,...,0,0,0,0,False,NaN,False,True,True,True
7,E008,Lisa Thomas,Sales,NaN,0.0,NaN,2039-09-26,peter.wilson@company.com,97455859430,NaN,...,1,0,0,0,True,company.com,True,False,False,False
8,E009,James Miller,NaN,150.0,9000.0,0.0,2020-09-13,zainab.martin@yahoo.com,97433138535,NaN,...,0,0,0,0,True,yahoo.com,True,False,True,True
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,97460281693,Female,...,0,0,0,0,True,yahoo.com,True,False,False,True

# 🟠 LEVEL 8 — Outlier Detection

# Task 26 — Detect Salary Outliers

**Objective:   Identify unusually low or high salaries using the Interquartile Range (IQR) method.**

**Approach:**
1. **Calculate the first quartile (`Q1`) using the 25th percentile.**
2. **Calculate the third quartile (`Q3`) using the 75th percentile.**
3. **Calculate the IQR.**
4. **Calculate the lower and upper outlier boundaries.**
5. **Create a new column named `salary_outlier` to identify potential outliers.**

**Formulas:**
- **`IQR = Q3 - Q1`**
- **`Lower Boundary = Q1 - (1.5 × IQR)`**
- **`Upper Boundary = Q3 + (1.5 × IQR)`**

**Expected result:**
- **`True` — salary is below the lower boundary or above the upper boundary.**
- **`False` — salary is within the boundaries.**

**Important:   Identify potential outliers without immediately deleting or modifying the original salary values.**

In [436]:
Q1 = df["salary"].quantile(0.25)
Q3 = df["salary"].quantile(0.75)
IQR = Q3-Q1
lower = Q1 - (1.5 * IQR)
upper = Q3 + (1.5 * IQR)
df["salary_outlier"] = ((df["salary"] < lower) | (df["salary"] > upper)).where(df["salary"].notna(), np.nan)
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower boundary:", lower)
print("Upper boundary:", upper)
df.head(10)

Q1: 5250.0
Q3: 7500.0
IQR: 2250.0
Lower boundary: 1875.0
Upper boundary: 10875.0

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,...,salary_missing,email_missing,phone_missing,email_valid,email_domain,phone_valid,age_valid,salary_valid,bonus_valid,salary_outlier
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,...,0,0,0,True,hotmail.com,True,True,True,True,False
1,E002,Mary Johnson,IT,30.0,16000.0,NaN,2040-09-07,joseph.yusuf@gmail.com,97478242882,Female,...,0,0,0,True,gmail.com,True,True,True,False,True
2,E003,NaN,IT,35.0,7500.0,NaN,2020-03-19,mary.brown@yahoo,97437773911,Female,...,0,0,0,False,yahoo,True,True,True,False,False
3,E004,Sara Khan,HR,NaN,NaN,500.0,2020-01-13,daniel.johnson@yahoo.com,97437855874,Female,...,1,0,0,True,yahoo.com,True,False,False,True,NaN
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,97459951676,Male,...,0,0,0,True,hotmail.com,True,True,True,False,False
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,97460281693,Male,...,0,0,0,True,yahoo.com,True,False,True,False,False
6,E007,David Wilson,Sales,29.0,7200.0,1200.0,NaT,john.davishotmail.com,NaN,Female,...,0,0,0,False,NaN,False,True,True,True,False
7,E008,Lisa Thomas,Sales,NaN,0.0,NaN,2039-09-26,peter.wilson@company.com,97455859430,NaN,...,0,0,0,True,company.com,True,False,False,False,True
8,E009,James Miller,NaN,150.0,9000.0,0.0,2020-09-13,zainab.martin@yahoo.com,97433138535,NaN,...,0,0,0,True,yahoo.com,True,False,True,True,False
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,97460281693,Female,...,0,0,0,True,yahoo.com,True,False,False,True,True

# 🟠 LEVEL 8 — Outlier Detection

# Task 27 — Detect Age Outliers

**Objective:   Identify unusually low or high employee ages using the Interquartile Range (IQR) method.**

**Approach:**
1. **Calculate the first quartile (`Q1`) using the 25th percentile.**
2. **Calculate the third quartile (`Q3`) using the 75th percentile.**
3. **Calculate the IQR.**
4. **Calculate the lower and upper outlier boundaries.**
5. **Create a new column named `age_outlier` to identify potential outliers.**

**Formulas:**
- **`IQR = Q3 - Q1`**
- **`Lower Boundary = Q1 - (1.5 × IQR)`**
- **`Upper Boundary = Q3 + (1.5 × IQR)`**

**Expected result:**
- **`True` — age is below the lower boundary or above the upper boundary.**
- **`False` — age is within the boundaries.**

**Important:   Identify potential outliers without immediately deleting or modifying the original age values.**

In [437]:
Q1 = df["age"].quantile(0.25)
Q3 = df["age"].quantile(0.75)
IQR = Q3-Q1
lower = Q1 - (1.5 * IQR)
upper = Q3 + (1.5 * IQR)
df["age_outlier"] = ((df["age"] < lower) | (df["age"] > upper)).where(df["age"].notna(), np.nan)
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower boundary:", lower)
print("Upper boundary:", upper)

df.head(10)

Q1: 26.0
Q3: 41.0
IQR: 15.0
Lower boundary: 3.5
Upper boundary: 63.5

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,...,email_missing,phone_missing,email_valid,email_domain,phone_valid,age_valid,salary_valid,bonus_valid,salary_outlier,age_outlier
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,...,0,0,True,hotmail.com,True,True,True,True,False,False
1,E002,Mary Johnson,IT,30.0,16000.0,NaN,2040-09-07,joseph.yusuf@gmail.com,97478242882,Female,...,0,0,True,gmail.com,True,True,True,False,True,False
2,E003,NaN,IT,35.0,7500.0,NaN,2020-03-19,mary.brown@yahoo,97437773911,Female,...,0,0,False,yahoo,True,True,True,False,False,False
3,E004,Sara Khan,HR,NaN,NaN,500.0,2020-01-13,daniel.johnson@yahoo.com,97437855874,Female,...,0,0,True,yahoo.com,True,False,False,True,NaN,NaN
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,97459951676,Male,...,0,0,True,hotmail.com,True,True,True,False,False,False
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,97460281693,Male,...,0,0,True,yahoo.com,True,False,True,False,False,NaN
6,E007,David Wilson,Sales,29.0,7200.0,1200.0,NaT,john.davishotmail.com,NaN,Female,...,0,0,False,NaN,False,True,True,True,False,False
7,E008,Lisa Thomas,Sales,NaN,0.0,NaN,2039-09-26,peter.wilson@company.com,97455859430,NaN,...,0,0,True,company.com,True,False,False,False,True,NaN
8,E009,James Miller,NaN,150.0,9000.0,0.0,2020-09-13,zainab.martin@yahoo.com,97433138535,NaN,...,0,0,True,yahoo.com,True,False,True,True,False,True
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,97460281693,Female,...,0,0,True,yahoo.com,True,False,False,True,True,True

# 🔴 LEVEL 9 — Duplicate Cleaning

# Task 28 — Find Duplicate Rows

**Objective:  Identify duplicate rows in the dataset.**

**Method:**
- **Use `df.duplicated()` to check whether each row duplicates a previous row.**
- **Returns `True` for duplicate rows and `False` for non-duplicate rows.**

**Task:**
- **Identify duplicate rows without deleting them immediately.**
- **Review the results before deciding how to handle duplicates.**

**Important:   By default, `df.duplicated()` considers all columns when checking for duplicate rows and marks the first occurrence as `False`.**

In [438]:
check_duplicate = df.duplicated()
check_duplicate

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499     True
Length: 500, dtype: bool

# 🔴 LEVEL 9 — Duplicate Cleaning

# Task 29 — Find Duplicate Employee IDs

**Objective:  Identify duplicate employee IDs in the dataset.**

**Column Checked:** `employee_id`

**Task:**
- **Check the `employee_id` column for duplicate values.**
- **Identify employee IDs that appear more than once.**

**Expected Result:**
- **`E015` and `E500` appears more than once in the dataset.**
- **Duplicate employee IDs are identified without deleting any records.**

In [439]:
duplicate_employee_id = df[df.duplicated(subset="employee_id", keep=False)]
duplicate_employee_id

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,...,email_missing,phone_missing,email_valid,email_domain,phone_valid,age_valid,salary_valid,bonus_valid,salary_outlier,age_outlier
14,E015,Daniel Wilson,IT,40.0,7000.0,-50.0,2019-10-14,lisa.ahmed@hotmail.com,97445192493,Male,...,0,0,True,hotmail.com,True,True,True,False,False,False
15,E015,Aisha Khan,IT,33.0,6500.0,NaN,2022-07-02,adam.thomas@hotmail.com,97472545481,NaN,...,0,0,True,hotmail.com,True,True,True,False,False,False
498,E500,Hana Davis,Operations,38.0,6200.0,0.0,2023-10-16,john..smith@gmail.com,97474685012,Male,...,0,0,True,gmail.com,True,True,True,True,False,False
499,E500,Hana Davis,Operations,38.0,6200.0,0.0,2023-10-16,john..smith@gmail.com,97474685012,Male,...,0,0,True,gmail.com,True,True,True,True,False,False

# 🔴 LEVEL 9 — Duplicate Cleaning

# Task 30 — Remove Exact Duplicate Rows

**Objective:   Remove exact duplicate rows while preserving records that require further investigation.**

**Approach:**
- **Counted the exact duplicate rows using `df.duplicated().sum()`.**
- **Displayed all rows involved in duplication using `df.duplicated(keep=False)`.**
- **Used `df.drop_duplicates()` to remove exact duplicate rows.**
- **Rechecked the dataset to confirm that no exact duplicate rows remained.**

**Results:**
- **Exact duplicate occurrences before cleaning: 1**
- **Rows involved in the duplication: 2**
- **Exact duplicate occurrences after cleaning: 0**

**Duplicate Employee ID Investigation:**
- **`E500`: The two records had identical details, so one duplicate record was removed.**
- **`E015`: The records had different details, so both were retained for further investigation.**

**Conclusion:   Exact duplicate rows were removed successfully. Records with duplicate employee IDs were not automatically deleted; they were reviewed based on their details.**

In [440]:
number_of_exact_duplicate = df.duplicated().sum()
exact_duplicate_rows = df[df.duplicated(keep=False)]
print("Number of exact duplicate :" , number_of_exact_duplicate)
exact_duplicate_rows

Number of exact duplicate : 1

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,...,email_missing,phone_missing,email_valid,email_domain,phone_valid,age_valid,salary_valid,bonus_valid,salary_outlier,age_outlier
498,E500,Hana Davis,Operations,38.0,6200.0,0.0,2023-10-16,john..smith@gmail.com,97474685012,Male,...,0,0,True,gmail.com,True,True,True,True,False,False
499,E500,Hana Davis,Operations,38.0,6200.0,0.0,2023-10-16,john..smith@gmail.com,97474685012,Male,...,0,0,True,gmail.com,True,True,True,True,False,False

In [441]:
df = df.drop_duplicates()
number_of_exact_duplicate = df.duplicated().sum()
print("Number of exact duplicate :" , number_of_exact_duplicate)

Number of exact duplicate : 0

# 🔴 LEVEL 10 — Advanced Cleaning

# Task 31 — Clean Invalid Dates

**Objective:** Convert date values into a proper datetime format and identify valid and invalid dates.

**Examples:**

**Valid dates:**
- `2020-01-15`
- `15/02/2021`
- `March 10 2020`
- `2020/13/01` → `2020-01-13`

**Invalid dates:**
- `invalid`

**Tasks:**
- Convert the `join_date` column into datetime format.
- Use `format="mixed"` to support different date formats.
- Use `dayfirst=True` to help interpret dates where the day comes before the month.
- Use `errors="coerce"` to convert unrecognized or invalid dates into `NaT`.
- Create a new column named `join_date_valid`.

**Expected Result:**
- `True` — the date was successfully converted.
- `False` — the date is missing or could not be converted.

**Important:** Do not delete invalid dates immediately. Identify them for further review.

In [442]:
df["join_date"] = pd.to_datetime(df["join_date"], errors="coerce",format="mixed", dayfirst=True)
df["join_date_valid"] = df["join_date"].notna()
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,...,phone_missing,email_valid,email_domain,phone_valid,age_valid,salary_valid,bonus_valid,salary_outlier,age_outlier,join_date_valid
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,...,0,True,hotmail.com,True,True,True,True,False,False,False
1,E002,Mary Johnson,IT,30.0,16000.0,NaN,2040-09-07,joseph.yusuf@gmail.com,97478242882,Female,...,0,True,gmail.com,True,True,True,False,True,False,True
2,E003,NaN,IT,35.0,7500.0,NaN,2020-03-19,mary.brown@yahoo,97437773911,Female,...,0,False,yahoo,True,True,True,False,False,False,True
3,E004,Sara Khan,HR,NaN,NaN,500.0,2020-01-13,daniel.johnson@yahoo.com,97437855874,Female,...,0,True,yahoo.com,True,False,False,True,NaN,NaN,True
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,97459951676,Male,...,0,True,hotmail.com,True,True,True,False,False,False,True
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,97460281693,Male,...,0,True,yahoo.com,True,False,True,False,False,NaN,True
6,E007,David Wilson,Sales,29.0,7200.0,1200.0,NaT,john.davishotmail.com,NaN,Female,...,0,False,NaN,False,True,True,True,False,False,False
7,E008,Lisa Thomas,Sales,NaN,0.0,NaN,2039-09-26,peter.wilson@company.com,97455859430,NaN,...,0,True,company.com,True,False,False,False,True,NaN,True
8,E009,James Miller,NaN,150.0,9000.0,0.0,2020-09-13,zainab.martin@yahoo.com,97433138535,NaN,...,0,True,yahoo.com,True,False,True,True,False,True,True
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,97460281693,Female,...,0,True,yahoo.com,True,False,False,True,True,True,True

# 🔴 LEVEL 10 — Advanced Cleaning

# Task 33 — Detect Future Join Dates

**Objective:   Identify employees whose join dates occur after today's date.**

**Tasks:**
- **Get today's date using `pd.Timestamp.today().normalize()`.**
- **Compare each `join_date` with today's date.**
- **Create a new column named `future_join_date`.**

**Expected Result:**
- **`True` — the join date is in the future.**
- **`False` — the join date is today or in the past.**

**Important:** Do not delete future join dates automatically. Flag them for further investigation.**

In [443]:
today = pd.Timestamp.today().normalize()
print(today)
df["future_join_date"] = df["join_date"] > today
df.head()

2026-10-26 00:00:00

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,...,email_valid,email_domain,phone_valid,age_valid,salary_valid,bonus_valid,salary_outlier,age_outlier,join_date_valid,future_join_date
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,...,True,hotmail.com,True,True,True,True,False,False,False,False
1,E002,Mary Johnson,IT,30.0,16000.0,NaN,2040-09-07,joseph.yusuf@gmail.com,97478242882,Female,...,True,gmail.com,True,True,True,False,True,False,True,True
2,E003,NaN,IT,35.0,7500.0,NaN,2020-03-19,mary.brown@yahoo,97437773911,Female,...,False,yahoo,True,True,True,False,False,False,True,False
3,E004,Sara Khan,HR,NaN,NaN,500.0,2020-01-13,daniel.johnson@yahoo.com,97437855874,Female,...,True,yahoo.com,True,False,False,True,NaN,NaN,True,False
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,97459951676,Male,...,True,hotmail.com,True,True,True,False,False,False,True,False

# 🔴 LEVEL 10 — Advanced Cleaning

# Task 34 — Standardize All Categorical Columns

**Objective:   Ensure categorical columns contain only the specified allowed values.**

**Allowed Values:**
- **`department`: `IT`, `HR`, `Sales`, `Finance`, `Operations`, `Marketing`**
- **`gender`: `Male`, `Female`, `Other`**
- **`status`: `Active`, `Inactive`**

**Tasks:**
- **Check each categorical column against its allowed values.**
- **Retain values that match the approved categories.**
- **Replace any other value with `NaN`.**

**Expected Result:**
- **Only the specified values remain in each column.**
- **Unexpected values become `NaN`.**
- **Existing missing values remain missing.**

In [444]:
#department
df["department"] = df["department"].where(df["department"].isin(['IT', 'HR', 'Sales','Finance', 'Operations', 'Marketing']), np.nan)
print(df["department"].unique())
#gender
df["gender"] = df["gender"].where(df["gender"].isin(['Male', 'Female' ,'Other']), np.nan)
print(df["gender"].unique())
#status
df["status"] = df["status"].where(df["status"].isin(['Active', 'Inactive']), np.nan)
print(df["status"].unique())

<StringArray>
['IT', 'HR', 'Sales', nan, 'Finance', 'Operations', 'Marketing']
Length: 7, dtype: str
<StringArray>
['Male', 'Female', nan, 'Other']
Length: 4, dtype: str
<StringArray>
[nan, 'Active', 'Inactive']
Length: 3, dtype: str

# 🔴 LEVEL 11 — Advanced Conditional Cleaning


# Task 35 — Create Salary Band

**Objective:   Categorize employees into salary bands based on their salary.**

**Rules:**
- **Salary below `6000` → `Low`**
- **Salary from `6000` to `7999` → `Medium`**
- **Salary `8000` or above → `High`**

**Tasks:**
- **Define conditions for each salary band.**
- **Use `np.select()` to assign the appropriate label.**
- **Store the result in a new column named `salary_band`.**

**Expected Result:**
- **Each valid salary is assigned to `Low`, `Medium`, or `High`.**
- **Missing salaries remain missing.**

In [445]:
#Method 1 — np.select()
category = (
    df["salary"] < 6000,
    df["salary"].between(6000,7999, inclusive="both"),
    df["salary"] >= 8000
)
labels = ['Low', 'Medium', 'High']
df["salary_band"] = np.select(category, labels, default=pd.NA)

#Method 2 — pd.cut()
df["salary_band2"] = pd.cut(
    df["salary"],
    bins=[-float("inf"), 6000, 8000, float("inf")],
    labels=["Low", "Medium", "High"],
    right=False
)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,...,phone_valid,age_valid,salary_valid,bonus_valid,salary_outlier,age_outlier,join_date_valid,future_join_date,salary_band,salary_band2
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,...,True,True,True,True,False,False,False,False,Low,Low
1,E002,Mary Johnson,IT,30.0,16000.0,NaN,2040-09-07,joseph.yusuf@gmail.com,97478242882,Female,...,True,True,True,False,True,False,True,True,High,High
2,E003,NaN,IT,35.0,7500.0,NaN,2020-03-19,mary.brown@yahoo,97437773911,Female,...,True,True,True,False,False,False,True,False,Medium,Medium
3,E004,Sara Khan,HR,NaN,NaN,500.0,2020-01-13,daniel.johnson@yahoo.com,97437855874,Female,...,True,False,False,True,NaN,NaN,True,False,NaN,NaN
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,97459951676,Male,...,True,True,True,False,False,False,True,False,High,High
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,97460281693,Male,...,True,False,True,False,False,NaN,True,False,Medium,Medium
6,E007,David Wilson,Sales,29.0,7200.0,1200.0,NaT,john.davishotmail.com,NaN,Female,...,False,True,True,True,False,False,False,False,Medium,Medium
7,E008,Lisa Thomas,Sales,NaN,0.0,NaN,2039-09-26,peter.wilson@company.com,97455859430,NaN,...,True,False,False,False,True,NaN,True,True,Low,Low
8,E009,James Miller,NaN,150.0,9000.0,0.0,2020-09-13,zainab.martin@yahoo.com,97433138535,NaN,...,True,False,True,True,False,True,True,False,High,High
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,97460281693,Female,...,True,False,False,True,True,True,True,False,Low,Low

# 🔴 LEVEL 11 — Advanced Conditional Cleaning

# Task 36 — Create Employee Age Group

**Objective:  Categorize employees into age groups based on their age.**

**Age Group Rules:**
- **18–25 → `Young`**
- **26–35 → `Early Career`**
- **36–50 → `Mid Career`**
- **51–65 → `Senior`**

**Tasks:**
- **Define age intervals using `pd.cut()`.**
- **Assign the appropriate label to each interval.**
- **Store the result in a new column named `age_group`.**

**Expected Result:**
- **Ages from 18 to 65 are assigned to the correct age group.**
- **Ages below 18, above 65, and missing ages remain `NaN`.**

In [446]:
df["age_group"] = pd.cut(df["age"],bins=[17,25,35,50,65], labels = ['Young', 'Early Career', 'Mid Career', 'Senior'], right=True, include_lowest=True)
df.head(10)

,employee_id,name,department,age,salary,bonus,join_date,email,phone,gender,...,age_valid,salary_valid,bonus_valid,salary_outlier,age_outlier,join_date_valid,future_join_date,salary_band,salary_band2,age_group
0,E001,John Smith,IT,25.0,5000.0,500.0,NaT,noor.martin@hotmail.com,97474793157,Male,...,True,True,True,False,False,False,False,Low,Low,Young
1,E002,Mary Johnson,IT,30.0,16000.0,NaN,2040-09-07,joseph.yusuf@gmail.com,97478242882,Female,...,True,True,False,True,False,True,True,High,High,Early Career
2,E003,NaN,IT,35.0,7500.0,NaN,2020-03-19,mary.brown@yahoo,97437773911,Female,...,True,True,False,False,False,True,False,Medium,Medium,Early Career
3,E004,Sara Khan,HR,NaN,NaN,500.0,2020-01-13,daniel.johnson@yahoo.com,97437855874,Female,...,False,False,True,NaN,NaN,True,False,NaN,NaN,NaN
4,E005,Robert Brown,HR,42.0,8000.0,NaN,2024-05-18,ali.thomas@hotmail.com,97459951676,Male,...,True,True,False,False,False,True,False,High,High,Mid Career
5,E006,Mohammed Hassan,Sales,NaN,6500.0,-50.0,2020-10-23,aisha.johnson@yahoo.com,97460281693,Male,...,False,True,False,False,NaN,True,False,Medium,Medium,NaN
6,E007,David Wilson,Sales,29.0,7200.0,1200.0,NaT,john.davishotmail.com,NaN,Female,...,True,True,True,False,False,False,False,Medium,Medium,Early Career
7,E008,Lisa Thomas,Sales,NaN,0.0,NaN,2039-09-26,peter.wilson@company.com,97455859430,NaN,...,False,False,False,True,NaN,True,True,Low,Low,NaN
8,E009,James Miller,NaN,150.0,9000.0,0.0,2020-09-13,zainab.martin@yahoo.com,97433138535,NaN,...,False,True,True,False,True,True,False,High,High,NaN
9,E010,Emma Davis,Finance,-5.0,-5000.0,500.0,2020-05-19,adam.anderson@yahoo.com,97460281693,Female,...,False,False,True,True,True,True,False,Low,Low,NaN

# 🔴 LEVEL 11 — Advanced Conditional Cleaning

# Task 37 — Create Employee Review Status

**Objective:   Assign an overall review status to each employee based on data validation results.**

**Rules:**
- **`Good`: All six validation checks pass.**
- **`Needs Review`: At least one validation check fails.**

**Validation Columns:**
- **`age_valid`**
- **`salary_valid`**
- **`bonus_valid`**
- **`email_valid`**
- **`phone_valid`**
- **`join_date_valid`**

**Tasks:**
- **Select the six validation columns.**
- **Check whether all validations pass for each employee.**
- **Use `np.where()` to assign `Good` or `Needs Review`.**
- **Store the result in a new column named `review`.**

**Expected Result:**
- **Employees who pass all six checks are marked `Good`.**
- **Employees who fail one or more checks are marked `Needs Review`.**

In [447]:
review = ['age_valid','salary_valid','bonus_valid','email_valid','phone_valid','join_date_valid']
df["review"] = np.where(df[review].all(axis=1), 'Good', 'Needs Review')
df[['age','salary','bonus','email','phone','join_date','age_valid','salary_valid','bonus_valid','email_valid','phone_valid','join_date_valid','review']].tail(10)

,age,salary,bonus,email,phone,join_date,age_valid,salary_valid,bonus_valid,email_valid,phone_valid,join_date_valid,review
489,42.0,8500.0,250.0,hana.ali@hotmail.com,97447538598,2023-03-25,True,True,True,True,True,True,Good
490,29.0,6500.0,500.0,fatima.taylor@company.com,97455423650,2020-01-23,True,True,True,True,True,True,Good
491,36.0,NaN,NaN,fatima.davis@hotmail.com,97461387776,2024-01-09,True,False,False,True,True,True,Needs Review
492,NaN,5500.0,500.0,noemail@,NaN,2024-03-01,False,True,True,False,False,True,Needs Review
493,18.0,9000.0,NaN,NaN,97435193155,2021-05-25,True,True,False,False,True,True,Needs Review
494,NaN,6250.0,500.0,mary.ali@company.com,97461054008,NaT,False,True,True,True,True,False,Needs Review
495,45.0,NaN,-50.0,emma.taylor@company.com,97431753140,2019-09-02,True,False,False,True,True,True,Needs Review
496,32.0,4800.0,1000.0,ryan.taylor@hotmail.com,97455872645,2020-02-18,True,True,True,True,True,True,Good
497,27.0,NaN,300.0,amira.moore@gmail.com,97467401535,2020-12-15,True,False,True,True,True,True,Needs Review
498,38.0,6200.0,0.0,john..smith@gmail.com,97474685012,2023-10-16,True,True,True,True,True,True,Good

# 🟣 LEVEL 12 — Complete Data Quality Report

# Task 38 — Create a Complete Data Quality Report

**Objective:  Create a summary table showing missing, invalid, and duplicate values for selected employee data columns.**

**Report Metrics:**
- **`missing`: Number of missing values in each column.**
- **`invalid`: Number of values failing the available validation checks.**
- **`duplicates`: Number of repeated values within each column.**

**Tasks:**
- **Count missing values using `isna().sum()`.**
- **Count invalid values using the existing validation flags for age, salary, bonus, email, phone, and join date.**
- **Count repeated values within each column using `duplicated().sum()`.**
- **Combine the results into a single summary DataFrame.**

**Important Note:  Invalid counts for `name`, `department`, `gender`, and `status` remain zero because separate validation checks have not been defined for these columns.**

**Expected Result:**
- **All 11 selected columns appear in the report.**
- **Missing, invalid, and duplicate counts are displayed separately.**
- **Invalid counts reflect the available validation checks.**

In [448]:
summary_columns = ['employee_id','name','department','age','salary','bonus','join_date','email','phone','gender','status']

missing = df[summary_columns].isna().sum()

invalid = pd.Series(0, index = summary_columns, dtype = "int")
columns = ['age_valid','salary_valid','bonus_valid','email_valid','phone_valid','join_date_valid']

for cl in columns:
     count = (~df[cl]).sum()
     if cl == 'age_valid':
          invalid['age'] = count
     elif cl == 'salary_valid' :
          invalid['salary'] = count
     elif cl == 'bonus_valid' :
               invalid['bonus'] = count
     elif cl == 'email_valid' :
               invalid['email'] = count
     elif cl == 'phone_valid' :
               invalid['phone'] = count
     else :
               invalid['join_date'] = count

duplicates = pd.Series(0, index = summary_columns, dtype = "int")
for cl in summary_columns :
        count = df[cl].duplicated().sum()
        duplicates[cl] = count

summary = pd.DataFrame({
        "missing" : missing,
        "invalid" : invalid,
        "duplicates" : duplicates
})
summary.reset_index(names = "Column_name")

    Column_name  missing  invalid  duplicates
0   employee_id        0        0           1
1          name       37        0         185
2    department        1        0         492
3           age      127      170         437
4        salary      130      157         452
5         bonus      164      203         488
6     join_date       46       46          97
7         email       20       59          59
8         phone       46      135          55
9        gender      111        0         495
10       status       97        0         496

# 🟢 Bonus Task — Handle Missing Values

**Objective:   Handle missing values using appropriate strategies based on the meaning and type of each column.**

**Approach:**
- **Bonus:   Fill missing values with `0`, assuming a missing bonus means no bonus was paid.**
- **Age:   Fill missing values with the median age.**
- **Salary:   Fill missing values with the median salary.**
- **Department, Gender, Status:   Fill missing values with the mode (most frequent value), when available.**

**Important Note:   Missing-value handling depends on business meaning. Zero is appropriate for bonus only when a missing value genuinely means no bonus. Median and mode imputation are choices that should be justified for the dataset.**

**Expected Result:   Missing values in the selected columns are handled according to the chosen rules.**

In [449]:
df["bonus"] = df["bonus"].fillna(0)
df["age"] = df["age"].fillna(df["age"].median())
df["salary"] = df["salary"].fillna(df["salary"].median())

for cl in ["department", "gender", "status"]:
    if df[cl].notna().any():
        df[cl] = df[cl].fillna(df[cl].mode()[0])

# 🔵 Final Master Task — Export Cleaned Data to Excel

**Objective:   Export the final cleaned DataFrame `clean_df` to an Excel file.**

**Tasks:**
- **Export `clean_df` to `cleaned_employee_data.xlsx`.**
- **Exclude the DataFrame index from the Excel file.**

**Expected Result:   An Excel file containing the cleaned employee dataset.**

In [450]:
clean_df = df.copy()
clean_df.to_excel(r"D:\Private\555 sha\P\pandas-data-cleaning-project\data\cleaned_data.xlsx", index=False)